### ISSUE TITLE
INNODB_METRICS    buffer_page_read_XXX processing

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#107]
Hi,

Innodb metrics tracks pages which are being read and written which is very helpful for performance analyses, ie understand what you're bound by reading undo space etc.

mysql> select  name,count from innodb_metrics where name  like "buffer_page_%";
+-----------------------------------------+---------+
| name                                    | count   |
+-----------------------------------------+---------+
| buffer_pages_created                    |   98345 |
| buffer_pages_written                    | 3912493 |
| buffer_pages_read                       | 3864202 |
| buffer_page_read_index_leaf             | 1947236 |
| buffer_page_read_index_non_leaf         |    3307 |
| buffer_page_read_index_ibuf_leaf        | 1094490 |
| buffer_page_read_index_ibuf_non_leaf    |    3178 |
| buffer_page_read_undo_log               |  605859 |
| buffer_page_read_index_inode            |    8628 |
| buffer_page_read_ibuf_free_list         |       0 |
| buffer_page_read_ibuf_bitmap            |   18652 |
| buffer_page_read_system_page            |  168338 |
| buffer_page_read_trx_system             |    2065 |
| buffer_page_read_fsp_hdr                |    4119 |
| buffer_page_read_xdes                   |    5652 |
| buffer_page_read_blob                   |       0 |
| buffer_page_read_zblob                  |       0 |
| buffer_page_read_zblob2                 |       0 |
| buffer_page_read_other                  |       0 |
| buffer_page_written_index_leaf          | 1922780 |
| buffer_page_written_index_non_leaf      |    2869 |
| buffer_page_written_index_ibuf_leaf     | 1202883 |
| buffer_page_written_index_ibuf_non_leaf |    7719 |
| buffer_page_written_undo_log            |  517163 |
| buffer_page_written_index_inode         |   11030 |
| buffer_page_written_ibuf_free_list      |       0 |
| buffer_page_written_ibuf_bitmap         |    3947 |
| buffer_page_written_system_page         |  227179 |
| buffer_page_written_trx_system          |    3079 |
| buffer_page_written_fsp_hdr             |    6400 |
| buffer_page_written_xdes                |    7153 |
| buffer_page_written_blob                |       0 |
| buffer_page_written_zblob               |       0 |
| buffer_page_written_zblob2              |       0 |
| buffer_page_written_other               |       0 |
+-----------------------------------------+---------+
35 rows in set (0.01 sec)

It would be good idea for  buffer_page_read_XXXX  to be put in the separate "dimension" so it is easy to plot all which are available.

**Comment by roman-vynar** [comment]
It is not necessary as it can be graphed like this 
```
{__name__=~\"buffer_page_read_.+\"}
```

**Comment by SuperQ** [comment]
@roman-vynar True, but it's better to have this split out with labels.

**Comment by SuperQ** [comment]
https://github.com/prometheus/mysqld_exporter/pull/109 up for review.

**Comment by SuperQ** [comment]
Replaced with https://github.com/prometheus/mysqld_exporter/pull/115

**Comment by SuperQ** [comment]
Fixed
