### ISSUE TITLE
Warning on start: «Unknown column 'SPACE_TYPE' in 'field list'»

### ISSUE THREAD

**Issue by nordicdyno** [prometheus/mysqld_exporter#122]
mysqld_exporter version: 0.8.0
mysql version: percona-server 5.6 on ubuntu
user: debian-sys-maint (all grants)

On start mysqld_exporter shows:

    ERRO[0000] Error scraping for collect.info_schema.innodb_sys_tablespaces: Error 1054: Unknown column 'SPACE_TYPE' in 'field list'  source=mysqld_exporter.go:288

it works after all, but maybe something is broken in my configuration?

**Comment by SuperQ** [comment]
Yes, this has already been fixed in master.  

https://github.com/prometheus/mysqld_exporter/issues/118

I will release a new 0.8.1 soon.
