### ISSUE TITLE
Aggregate INNODB_METRICS Metrics

### ISSUE THREAD

**Issue by grypyrg** [prometheus/mysqld_exporter#129]
Some `INNODB_METRICS` would better be aggregated.
(which are disabled by default and can be enabled with `innodb_monitor_enable` variable) 

Example:  `mysql_info_schema_innodb_metrics_buffer_buffer_.*`

To make it easy, you can just aggregate according to subsystem as listed in https://dev.mysql.com/doc/refman/5.6/en/innodb-information-schema-metrics-table.html

**Comment by grypyrg** [comment]
Maybe by subsystem is not that useful, many metrics are much different:

- `mysql_info_schema_innodb_metrics_buffer_buffer_LRU`
- `mysql_info_schema_innodb_metrics_buffer_pool_pages_(dirty|free|...)`

**Comment by SuperQ** [comment]
I originally made the innodb_metrics labeled by subsystem, but there were many cases where it didn't make sense.

**Comment by SuperQ** [comment]
So here's the aggregation that makes sense for subsystem=buffer `buffer_pool_pages.*`.
Total is the sum of data+misc+free.  But dirty seems like a separate metric.

**Comment by roman-vynar** [comment]
We have already `mysql_global_status_buffer_pool_pages` with `state` data, dirty, misc, free and `mysql_global_status_innodb_buffer_pool_bytes_data`, `mysql_global_status_innodb_buffer_pool_bytes_dirty`.
So there is no benefit in this from `innodb_metrics` at all.

**Comment by SuperQ** [comment]
@roman-vynar True, but that depends on which collectors are activated.  I think it's still worth it to correctly format in both places.

**Comment by roman-vynar** [comment]
Yep.

**Comment by SuperQ** [comment]
Fixed with #130
