### ISSUE TITLE
Add metrics for Galera based clusters

### ISSUE THREAD

**Issue by shamil** [prometheus/mysqld_exporter#131]
Hi,

It will be very helpful if the exporter expose Galera based variables, those that start with `wsrep_`. 
Or at least allow configuring the exporter to expose custom variables.

Thanks

**Comment by SuperQ** [comment]
The exporter already exposes everything from `SHOW GLOBAL STATUS` and `SHOW GLOBAL VARIABLES`.  That includes all of the `wsrep.*` values.  Is there something missing?

**Comment by shamil** [comment]
Yes, you are right. I should've RTFM
