### ISSUE TITLE
Protect MySQL Server from Overload - Limit number of Scrapes which can happen at the same time

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#133]
We have some cases when users have tens of thousands of tables, which means  the information_schema related scrapes  may take a long time,  causing folks to have 100+  information schema queries triggered by Prometheus to happen at the same time possibly driving server out of connections. 

Sometimes it happens only when server is under duress  rather than all the time which makes it a bad idea to simply disable this data collection. 

It would be great if I could configure what   exporter allows no more than N concurrent requests to handle in parallel,   so for example if there is more than 3 scrape requests are underway error is returned and data is unavailable rather than server being overloaded.

**Comment by SuperQ** [comment]
Yes, this is a good idea.  I wonder if there are any specific collectors we should lock on to avoid concurrent access to specific internals that generate server locks when scrapes happen.  For example the information_schema tables.

**Comment by PeterZaitsev** [comment]
Ben,

I would suggest the simple and safe solution first.  I had
information_schema as example hope you would agree at least with it :)

In reality I've seen some cases when  under high load SHOW GLOBAL STATUS
was taking 30+ seconds   -  It should not take that much in theory but I've
seen it.  And yes  this is already indication of Server very unhealthy but
we do not want server to be completely killed by monitoring.

On Wed, Jun 8, 2016 at 3:46 AM, Ben Kochie <notifications@github.com> wrote:

> Yes, this is a good idea. I wonder if there are any specific collectors we
> should lock on to avoid concurrent access to specific internals that
> generate server locks when scrapes happen. For example the
> information_schema tables.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/prometheus/mysqld_exporter/issues/133#issuecomment-224514158>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADe4oryyWXNR71_E3Jl6VPQQKatsbWs2ks5qJnNCgaJpZM4IwP02>
> .
>



-- 
Peter Zaitsev, CEO, Percona
Tel: +1 888 401 3401 ext 7360   Skype:  peter_zaitsev

**Comment by brian-brazil** [comment]
Is this something that might be left to per-user connection limits?

**Comment by SuperQ** [comment]
@brian-brazil That's probably a better way.  I could add that as a recommended setting to the `GRANT` in the README.

http://dev.mysql.com/doc/refman/5.6/en/user-resources.html

**Comment by SuperQ** [comment]
Committed: 

https://github.com/prometheus/mysqld_exporter/commit/88e7062f002a686586c035003cb4281b2a19d24a

**Comment by SuperQ** [comment]
This is a better solution, especially when you have multiple exporters hitting the same server, as PMM does.

**Comment by PeterZaitsev** [comment]
Hi,

I agree it is a good practice too and we can have it controlled in PMM.  In
my experience though it is tough to count on user to set things up
correctly.

In any case is not it a best practice to make sure there is an option to
limit how many concurrent connections server can accept  -  whenever you
look at MySQL Server, Apache or Nginx there is typically a limit you can set
No limit means you open things up for easy DOS

On Wed, Jun 8, 2016 at 9:22 AM, Brian Brazil <notifications@github.com>
wrote:

> Is this something that might be left to per-user connection limits?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/prometheus/mysqld_exporter/issues/133#issuecomment-224586807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADe4oqcmm8VW-mFDzAT_z1--7EvQqVPFks5qJsITgaJpZM4IwP02>
> .
>



-- 
Peter Zaitsev, CEO, Percona
Tel: +1 888 401 3401 ext 7360   Skype:  peter_zaitsev

**Comment by SuperQ** [comment]
The best practice here is for the service being monitored to be responsible for dealing with overload.  Exporters are supposed to be thin proxies for services that do not have native instrumentation.

Prometheus server maintains timeouts that must be less than the scrape interval.  This way scheduled scrapes do not happen in parallel.  I suppose we should double check that the cancel signal from the http/client library is getting sent up to the mysql connection to avoid zombie threads from piling up.

MySQL 5.7 allows `SET SESSION MAX_STATEMENT_TIME`, which could help here.

**Comment by SuperQ** [comment]
Yes, If the Prometheus server times out, the connection to the client library should cause the mysql connection to close instead of hanging around in the background.  If this isn't happening, we should try and fix that.

**Comment by PeterZaitsev** [comment]
Ben,

Closing MySQL connection does not stop query running.  This is why for
example newer MySQL clients  establish another connection and send KILL to
the running thread when you click CTRL-C

MySQL protocol is designed so  when client sent query to the server the
only thing it can do is to wait for result. Anything it tries to send to
server while query is already running will be ignored until that query
execution is complete.

On Wed, Jun 8, 2016 at 11:08 AM, Ben Kochie <notifications@github.com>
wrote:

> Yes, If the Prometheus server times out, the connection to the client
> library should cause the mysql connection to close instead of hanging
> around in the background. If this isn't happening, we should try and fix
> that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/prometheus/mysqld_exporter/issues/133#issuecomment-224619817>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADe4ogTjqnepJ_Dy3B1zEY9nELzeHjOlks5qJtrogaJpZM4IwP02>
> .
>



-- 
Peter Zaitsev, CEO, Percona
Tel: +1 888 401 3401 ext 7360   Skype:  peter_zaitsev
