### ISSUE TITLE
Custom Queries

### ISSUE THREAD

**Issue by gimler** [prometheus/mysqld_exporter#139]
it is possible to add his own query for a specific metric from a table?

**Comment by grobie** [comment]
Have a look at https://github.com/chop-dbhi/prometheus-sql.

**Comment by SuperQ** [comment]
That depends.  The mysqld_exporter is not for monitoring application metrics, only mysql internal metrics.  If the metric is something from information_schema, performance_schema, etc we can add that.  If it's from an application table it's inappropriate for the mysqld_exporter and you should use the tool @grobie mentioned.
