### ISSUE TITLE
Add galera cluster information metric

### ISSUE THREAD

**Issue by SuperQ** [prometheus/mysqld_exporter#140]
Adding a metric with the cluster info, including the `wsrep_cluster_state_uuid` is useful to detect nodes that have split-brain from the rest of the cluster.

**Comment by grypyrg** [comment]
I even remember having a split brain while both 'new clusters' have the same `wsrep_cluster_state_uuid`

**Comment by roman-vynar** [comment]
Galera wsrep_* vars are the part of whether `SHOW GLOBAL STATUS` or `SHOW GLOBAL VARIABLES`, so there is no need to do anything extra as we scrape those by default.

**Comment by bborysenko** [comment]
Actually not all. For example these ones from `SHOW GLOBAL STATUS`:

```
wsrep_cluster_state_uuid
wsrep_cluster_status
wsrep_incoming_addresses
wsrep_local_state_comment
wsrep_local_state_uuid
wsrep_provider_name
wsrep_provider_vendor
wsrep_provider_version
```

**Comment by roman-vynar** [comment]
Ah, indeed. Looks like they have to be put into labels of some info metric(s).

**Comment by bborysenko** [comment]
Just added PR #146 for the `wsrep_cluster_status`

**Comment by SuperQ** [comment]
@bborysenko Thanks, that's a good one.

I'll try and spend some time on the "info metrics" for the other variables.

**Comment by SuperQ** [comment]
Also related: https://github.com/prometheus/mysqld_exporter/pull/155

**Comment by SuperQ** [comment]
I think we have all of this handled in the `global_status` collector.  Please open a new issue if there is something missing.
