### ISSUE TITLE
mysql_global_status_connections keeps going up

### ISSUE THREAD

**Issue by waqark3389** [prometheus/mysqld_exporter#142]
With a MySQL server with no other activity from any other source except mysql_exporter why does the number of connections keep going up? 
I have set:
MAX_USER_CONNECTIONS to 3 as recommended. 

However this number keeps going up. Is it the case that when the queries are executed, the connection is left open, i.e. you are not logging back out?

**Comment by SuperQ** [comment]
Connections[0] is a counter, it always goes up, one for each connection to the mysqld.  It is not a gauge of the current threads connected.  The mysqld_exporter does not have any kind of connection pooling, and in order for it to support multiple prometheus servers polling simultaneously (HA enviornments)  it must open a new connection for each scrape.  It does close this connection at the completion of each scrape.

[0]: http://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Connections

**Comment by waqark3389** [comment]
Hi SuperQ,
No problem opening new connections, I think, however, that its not actually closing the connections. Were you not able to replicate this? 

Unless I am misunderstanding what connections represents i.e. It just goes up forever? Please see attached my graph for the connections metric from last week to day. 
https://snag.gy/JwBg1q.jpg

**Comment by matthiasr** [comment]
Correct, it goes up forever. That is the definition of a [counter](https://prometheus.io/docs/concepts/metric_types/#counter).

It represents the number of connection attempts since the server started. Closing connections plays no role in this metric.

**Comment by waqark3389** [comment]
Perfect, thank you for the explanation :)

**Comment by SuperQ** [comment]
FYI `mysql_global_status_threads_connected` is a gauge of current connections.  Of course this doesn't detect bursts of connections, since it is only updated when prometheus scrapes.  

Try `rate(mysql_global_status_connections[1m])`.  This will show you the connection rate in connections per second.

Here's a couple of good alerting examples that will allow you to monitor connections.

```
ALERT MySQLTooManyConnections
  IF mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80
  FOR 30m
  LABELS {
    service = "mysql",
    severity = "warning"
  }
  ANNOTATIONS {
    summary = "MySQL has too many connections",
    description = "The server has too many connections. {{$value}} > 80% for over 30 minutes",
  }
```

```
ALERT MySQLWillOverloadConnectionsSoon
  IF predict_linear(mysql_global_status_threads_connected[2m], 60*30) > mysql_global_variables_max_connections
  FOR 5m
  LABELS {
    service = "mysql",
    severity = "critical"
  }
  ANNOTATIONS {
    summary = "MySQL will overload connections soon",
    description = "The server will reach its connection limit in less than 30 minutes.",
  }
```
