### ISSUE TITLE
Please add replication slave channel monitoring

### ISSUE THREAD

**Issue by zerthimon** [prometheus/mysqld_exporter#143]
https://dev.mysql.com/doc/refman/5.7/en/replication-channels.html

Since mysql 5.7 it's become possible to have multiple masters replicating to the same slave.
It would be great if i could monitor slave values of each channel.

Edit:
Currenlty only the first configured channel can be monitored.

**Comment by roman-vynar** [comment]
It has been already implemented https://github.com/prometheus/mysqld_exporter/pull/134
Just not released.

**Comment by SuperQ** [comment]
Yea, I guess I should cut a new release.

**Comment by zerthimon** [comment]
Oh, that's cool, thanks!
