### ISSUE TITLE
allow paramaterization of DATA_SOURCE_NAME

### ISSUE THREAD

**Issue by tmc** [prometheus/mysqld_exporter#145]
Having this hardcoded means you can't run two mysqld_exporter processes for separate mysql instances in the same configuration namespace. While rare I have encountered this situation.

**Comment by brian-brazil** [comment]
We generally take the stance with Prometheus that this sort of issue should be handled in your configuration management, as we don't want to gradually grow full templating solutions in various places through the system.

Environment variables are not hard to change per-process.

**Comment by SuperQ** [comment]
It's also an option to use a `.my.cnf` style config file which you can template.

I don't know the exact configuration being used here, but it's recommended to run exporters over localhost to avoid networking issues between the exporter and the mysqld.
