### ISSUE TITLE
Broken user/client statistics for Percona Server

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/mysqld_exporter#148]
This commit broke user statistics for Percona Server https://github.com/prometheus/mysqld_exporter/pull/138/files#diff-1cfdb3ffdb1892d4e0c3e4ea1ee8af1bL13

MariaDB has one set of columns https://mariadb.com/kb/en/mariadb/information-schema-user_statistics-table/
Percona Server has different https://www.percona.com/doc/percona-server/5.5/diagnostics/user_stats.html#USER_STATISTICS

Now it only works with MariaDB.

The same thing with client statistics.

**Comment by SuperQ** [comment]
Tricky, it looks like there are a bunch of differences.  I guess we need to move this back to a `SELECT *` and handle all the variations.

**Comment by roman-vynar** [comment]
Heh, it neither works properly with MariaDB, e.g. `ROWS_SENT` is not the map to evaluate https://github.com/prometheus/mysqld_exporter/pull/138/files#diff-1cfdb3ffdb1892d4e0c3e4ea1ee8af1bL54

So yeah, `SELECT *` would be better to go back.
