### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by malikkal** [prometheus/mysqld_exporter#154]
Trying to use with mariadb running the exporter on the same host and getting the below error while starting via DSN or config file . Checked everything that I could think off and have hit the wall. Please help.

Error pinging mysqld: dial tcp [::1]:3306: getsockopt: connection refused

**Comment by SuperQ** [comment]
Hmm, I've not tested using ipv6 notation.

**Comment by malikkal** [comment]
Thanks much. That's probably when localhost was resolved. As ipv6 is disabled, I can correct the hosts file. I even tried with 127.0.0.1 plus the other interface the host has, but the error was still connection refused, though obviously the message slightly different.

**Comment by SuperQ** [comment]
It sounds like mariadb is not listening on localhost.

Can you paste the output of this command: 
```
ss -ltn '( sport = :3306 )'
```

**Comment by maheshmadpathi** [comment]
I'm facing the same issue.
```bash
prometheus | time="2017-02-03T13:22:52Z" level=error msg="Error sending alerts: Post http://localhost:9093/api/v1/alerts: dial tcp [::1]:9093: getsockopt: connection refused" alertmanager="http://localhost:9093/api/v1/alerts" count=1 source="notifier.go:335"
```

**Comment by SuperQ** [comment]
@maheshmadpathi That is a problem with your Prometheus alertmanager config, it has nothing to do with `mysqld_exporter`.
