### ISSUE TITLE
Pushing selected metrics from SHOW VARIABLES

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/mysqld_exporter#16]
Hello,

It would be great to push those numeric metrics from SHOW VARIABLES in order to use in the query expressions.

Some examples:
- thread_cache_size - useful to have a max size on the graph as a baseline along with the existing threads_cached and threads_created from SHOW GLOBAL STATUS
- max_connections - to calculate usage % for alerting, e.g. connections / max_connections * 100%
- read_only ON/OFF translated into 1/0 - you may want to see when MySQL node was in read-only mode
- table_open_cache
- query_cache_size
- thread_pool_size

Thanks,
Roman

**Comment by juliusv** [comment]
@SuperQ

**Comment by SuperQ** [comment]
Sure, this sounds like a good idea.  If you think of any more, dump them here.  I will likely use `SHOW GLOBAL VARIABLES` to avoid any thread local values.

**Comment by SuperQ** [comment]
PR: https://github.com/prometheus/mysqld_exporter/pull/21

**Comment by SuperQ** [comment]
PR Merged, will be in the 1.0 release.
