### ISSUE TITLE
no metric exported when mysql slave status "connecting"

### ISSUE THREAD

**Issue by rcabana** [prometheus/mysqld_exporter#164]
I noticed issues receiving metrics from the mysqld exporter when "Slave_IO_Running" is in "Connecting" state. When in "Yes" or "No" I do receive metrics.

```
             Slave_IO_Running: Connecting
            Slave_SQL_Running: Yes
```

**Comment by roman-vynar** [comment]
It should report 0 when it is in `Connecting` state https://github.com/prometheus/mysqld_exporter/blob/master/collector/collector.go#L39

**Comment by SuperQ** [comment]
@rcabana What version of mysqld_exporter are you running?
