### ISSUE TITLE
Metadata lock interrupts metrics collection

### ISSUE THREAD

**Issue by matthiasr** [prometheus/mysqld_exporter#167]
While a different connection holds a metadata lock, the exporter hangs on this query:

```
SELECT
                    TABLE_SCHEMA,
                    TABLE_NAME,
                    TABLE_TYPE,
                    ifnull(ENGINE, 'NONE') as ENGINE,
                    ifnull(VERSION, '0') as VERSION,
                    ifnull(ROW_FORMAT, 'NONE') as ROW_FORMAT,
                    ifnull(TABLE_ROWS, '0') as TABLE_ROWS,
                    ifnull(DATA_LENGTH, '0') as DATA_LENGTH,
                    ifnull(INDEX_LENGTH, '0') as INDEX_LENGTH,
                    ifnull(DATA_FREE, '0') as DATA_FREE,
                    ifnull(CREATE_OPTIONS, 'NONE') as CREATE_OPTIONS
                  FROM information_schema.tables
                  WHERE TABLE_SCHEMA = 'notifications' |
```

waiting for same metadata lock. Since no metrics are scrapeable, there is no more insight to be gained from Prometheus – specifically, the `mysql_up 1` doesn't make it to the server.

One way to avoid this would be to time out at some point and return what we have (or reconnect and carry on).

**Comment by SuperQ** [comment]
It's possible to send the go-sql-driver timeouts via the DSN string.

https://github.com/go-sql-driver/mysql#readtimeout
https://github.com/go-sql-driver/mysql#timeout

I don't know if there's a way to do per-query timeouts with the normal Golang driver.

**Comment by SuperQ** [comment]
@matthiasr Has this been tested to be "fixed" by setting the timeout?  I don't have a good reproduction case.

**Comment by grypyrg** [comment]
For metadata locks you have to set `lock_wait_timeout` : http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_lock_wait_timeout

**Comment by EdSchouten** [comment]
I also ran into this issue earlier today. Turns out we have one... interesting customer who has tens of thousands of tables in one database. Solved this by setting `-collect.info_schema.tables=false`.

**Comment by SuperQ** [comment]
@EdSchouten Can you give #252 a try?

**Comment by EdSchouten** [comment]
In our case it's not really the locking that's problematic; it's just that our MySQL server contains too many tables, more than we're willing to ingest in the first place. Setting a locking timeout won't really make a difference in our case. :-)
