### ISSUE TITLE
Error pinging mysqld

### ISSUE THREAD

**Issue by gl328518397** [prometheus/mysqld_exporter#174]
level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'prometheus'@'localhost' (using password: YES)" source="mysqld_exporter.go:252" 

what error ?

**Comment by gl328518397** [comment]
I have find reason,,my mysql version is 5.7/// hope it can support .

**Comment by SuperQ** [comment]
MySQL 5.7 is supported.

**Comment by strowi** [comment]
Hi,

i'm running into the same error with mysqld_exporter-0.9.0 + Percona5.7 and root-privileges. Here is the log

```
root@ubuntu:~# /opt/mysqld_exporter/mysqld_exporter -config.my-cnf=/root/.my.cnf 
INFO[0000] Starting mysqld_exporter (version=0.9.0, branch=master, revision=8400af20ccdbf6b5e0faa2c925c56c48cd78d70b)  source=mysqld_exporter.go:432
INFO[0000] Build context (go=go1.6.3, user=root@2c131c66ca20, date=20160926-18:28:09)  source=mysqld_exporter.go:433
ERRO[0000] Error pinging mysqld: Error 1698: Access denied for user 'root'@'localhost'  source=mysqld_exporter.go:252
INFO[0000] Listening on :9104                            source=mysqld_exporter.go:451
```

**Comment by SuperQ** [comment]
Check your DNS settings, if you turn off reverse DNS lookups, you need to grant `127.0.0.1` permission.

**Comment by strowi** [comment]
Thx! Seems i forgot about the skip-dns in my new setup.

**Comment by cRUSHr2012** [comment]
I had a similar problem, the file .my.cnf. had a password with '#' symbol in it, at the end. I am using Prometheus 1.5.0 and Percona 5.7

**Comment by SuperQ** [comment]
@cRUSHr2012 That sounds like a problem with the the golang ini file reader.  According to the docs anything after a `#` will be treated as a comment.  Doesn't look like standard quoting is possible either.

See: https://github.com/go-ini/ini/#comment

**Comment by NZQiu** [comment]
Got similar problem, using password which contains # symbol
After change, success.

**Comment by lohmag** [comment]
Can't find solution to this problem
`export "DATA_SOURCE_NAME='exporter:password@(localhost:3306)/'"
/usr/bin/mysqld_exporter -collect.binlog_size=true -collect.info_schema.processlist=true
INFO[0000] Starting mysqld_exporter (version=0.9.0, branch=master, revision=8400af20ccdbf6b5e0faa2c925c56c48cd78d70b)  source=mysqld_exporter.go:432
INFO[0000] Build context (go=go1.6.3, user=root@2c131c66ca20, date=20160926-18:28:09)  source=mysqld_exporter.go:433
ERRO[0000] Error pinging mysqld: Error 1045: Access denied for user ''exporter'@'127.0.0.1' (using password: YES)  source=mysqld_exporter.go:252
INFO[0000] Listening on :9104                            source=mysqld_exporter.go:451
`
Tryed to create ''exporter'@'127.0.0.1' and ''exporter'@'locahost' and ''exporter'@'%' users, allt of them at once< give them all kind of right including root - no chence.
I have Server version: 5.6.33-79.0-log Percona Server

**Comment by SuperQ** [comment]
@lohmag It looks like you have quotes around your variable export, this is invalid syntax.  It is making your username literally `'exporter`, not `exporter`.

Usage questions are best asked on https://groups.google.com/forum/#!aboutgroup/prometheus-users

**Comment by SuperQ** [comment]
@RobiD Please do not post unrelated help requests to closed issues.  For help with the exporter, I suggest you use our [community](https://prometheus.io/community/).

**Comment by michaelkoro** [comment]
Does anybody have a solution for this ?
Still having this issue with 0.11 version.

**Comment by AashishChughHome** [comment]
Facing same issue, anyone have a solution.

**Comment by SuperQ** [comment]
For those that keep posting to this issue these are likely configuration problems. Please review your configuration for typos. Check the ACLs and DNS lookup configuration on your MySQL server. Or look in the log files.

GitHub issues are reserved for bug reports and feature requests.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
