### ISSUE TITLE
Getting read tcp i/o time out

### ISSUE THREAD

**Issue by irocks04** [prometheus/mysqld_exporter#179]
Get http://rdcoriqa-percona2.ngnpr.den.vz.altidev.net:9104/metrics: read tcp 127.0.1.1:39265->127.0.1.1:9104: i/o timeout

I am able to curl from the host machine but not sure why the state shows down in prometheus status page.
Any idea on this?

FYI, I have this set up working absolutely fine in AWS , currently i am trying on verizon environment.

**Comment by SuperQ** [comment]
This seems like a local problem.  Also, it's not recommended to run the exporter on localhost with the Prometheus server.  Rather, localhost on the mysql server.
