### ISSUE TITLE
Don't log errors if metric is not supported

### ISSUE THREAD

**Issue by Firm** [prometheus/mysqld_exporter#182]
We use Percona MySQL 5.5 and have a lot of errors in /var/log/messages like:

`
Feb 17 08:41:31 db mysqld_exporter: time="2017-02-17T08:41:31Z" level=error msg="Error scraping for collect.perf_schema.tableiowaits: Error 1146: Table 'performance_schema.table_io_waits_summary_by_table' doesn't exist" source="mysqld_exporter.go:325"

Feb 17 08:41:31 db mysqld_exporter: time="2017-02-17T08:41:31Z" level=error msg="Error scraping for collect.perf_schema.indexiowaits: Error 1146: Table 'performance_schema.table_io_waits_summary_by_index_usage' doesn't exist" source="mysqld_exporter.go:331"

Feb 17 08:41:31 db mysqld_exporter: time="2017-02-17T08:41:31Z" level=error msg="Error scraping for collect.perf_schema.tablelocks: Error 1146: Table 'performance_schema.table_lock_waits_summary_by_table' doesn't exist" source="mysqld_exporter.go:337"

Feb 17 08:41:31 db mysqld_exporter: time="2017-02-17T08:41:31Z" level=error msg="Error scraping for collect.perf_schema.file_events: Error 1054: Unknown column 'SUM_TIMER_READ' in 'field list'" source="mysqld_exporter.go:355"
`

It would be wise to check version and/or if table/column exists.

Regards,
Alexander

**Comment by SuperQ** [comment]
These features, like `-collect.perf_schema.tableiowaits`, are off by default and are documented as being supported by 5.6 and newer.  You need to remove it from your configuration to avoid the error.

**Comment by Firm** [comment]
Thank you, missed this from install defaults.
