### ISSUE TITLE
Expose the MySQL addr as a label

### ISSUE THREAD

**Issue by frodenas** [prometheus/mysqld_exporter#185]
Is there any easy way to expose the MySQL address (from the `DATASOURCE_NAME`) as a metric label?

My exporters are not collocated with the MySQL server, they are on different vms, so from the metrics I can only get the `instance` label (that corresponds to the exporter IP address) and the `job` (and unfortunately it's the same for all my exporters as I'm using the `file_sd` mechanism). I know that I can do relabeling and add that label, but this is expensive, so I'm trying to avoid it, and will force me to hardcode somewhere at my scrape config those address.

If there isn't any easy way to do the above, would be adding an `addr` label to all metrics an useful feature? If yes, I'm willing to submit a PR adding this.

**Comment by brian-brazil** [comment]
> I know that I can do relabeling and add that label, but this is expensive, so I'm trying to avoid it

This is target relabelling, so it's effectively free.

> If there isn't any easy way to do the above, would be adding an addr label to all metrics an useful feature?

That's considered a major anti-pattern in Prometheus.

I'd suggest reading https://www.robustperception.io/controlling-the-instance-label/

**Comment by SuperQ** [comment]
Yes, this is a job for relabeling.

**Comment by frodenas** [comment]
Thanks for your answers. The challenge in my use case is how to do relabelling when using the service discovery approach, as I only get the address of the `mysqld_exporter`.

@brian-brazil One follow-up question, when you say "_effectively free_", I understand that the overhead for the prometheus server to do the relabeling is negligible, is that true?

**Comment by brian-brazil** [comment]
> The challenge in my use case is how to do relabelling when using the service discovery approach, as I only get the address of the mysqld_exporter.

A mysqld exporter can only talk to one mysqld, so that's fine. If you can get the addresses of all the mysqld_exporters you have all you need.

> One follow-up question, when you say "effectively free", I understand that the overhead for the prometheus server to do the relabeling is negligible, is that true?

Yes.
