### ISSUE TITLE
Issues with sql_mode=only_full_group_by in perf_schema_events_statements

### ISSUE THREAD

**Issue by galexrt** [prometheus/mysqld_exporter#200]
I'm getting errors in the logs:
```
time="2017-05-20T17:07:50Z" level=error msg="Error scraping for collect.perf_schema.eventsstatements: Error 1055: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'Q.DIGEST_TEXT' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" source="mysqld_exporter.go:359"
```
The query that's causing this seems to be: https://github.com/prometheus/mysqld_exporter/blob/82e9cb50ffcd99d49062a1bff3eb4e653eafa112/collector/perf_schema_events_statements.go#L13-L40

***

If you need any more info about this issue, please let me know.

**Comment by SuperQ** [comment]
[ONLY_FULL_GROUP_BY](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by) seems to be a new feature of MySQL >= 5.7.5.

We will need to fix this query in order to make this collector work with newer versions.
