### ISSUE TITLE
How to prevent mysqld_exporter from using ipv6 address to connect mysql?

### ISSUE THREAD

**Issue by justlooks** [prometheus/mysqld_exporter#201]
i installed mysqld_exporter on my mysql server, but it seems mysql_exporter use ipv6  connect mysql
i create connect user is localhost ,and how to disable mysql_exporter ipv6 function?

ERRO[55974] Error pinging mysqld: Error 1130: Host '::1' is not allowed to connect to this MySQL server  source="mysqld_exporter.go:268"
ERRO[55989] Error pinging mysqld: Error 1130: Host '::1' is not allowed to connect to this MySQL server  source="mysqld_exporter.go:268"

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name
tcp        0      0 127.0.0.11:41488            0.0.0.0:*                   LISTEN      -
tcp        0      0 :::3306                     :::*                        LISTEN      -
tcp        0      0 :::9100                     :::*                        LISTEN      8/node_exporter
tcp        0      0 :::9104                     :::*                        LISTEN      9/mysqld_exporter
udp        0      0 127.0.0.11:59217            0.0.0.0:*                               -

**Comment by SuperQ** [comment]
It sounds like you are using a newer version of MySQL that disables DNS lookups for connections by default.  The problem is not IPv6 in this case.  You either need to enable DNS lookups, or adjust the grant to add the IP to the allowed list.
