### ISSUE TITLE
Monitoring Windows based MySQL database

### ISSUE THREAD

**Issue by MartynKeigher** [prometheus/mysqld_exporter#202]
_tag: Help Wanted please! (This is not an issue!)_

Hey all, 

I setup Prometheus today to feed stats into an already existing Grafana board. My MySQL instance is running on windows and the docs are really lacking here. Can someone provide me a sample my.cnf file that the **mysqld_exporter.exe** is looking for please, or at least point in the right direction as to how i would find one??

Thanks.

**Comment by SuperQ** [comment]
The my.cnf file should look like this:
```
[client]
user=username
password=password
```

This comes from the [parseMycnf](https://github.com/prometheus/mysqld_exporter/blob/master/mysqld_exporter.go#L467-L488) function.

**Comment by MartynKeigher** [comment]
Awesome!! Thank you so much!!

Couldn't find any documentation on that anywhere!!

For those interested, here is a powershell script to Create a Scheduled Task so that the executable runs (with its config) on startup. _(I did initially set this up as a Windows Service but ran into issues, but the Sched. Task should works as a semi-viable option!)_

```
$action = New-ScheduledTaskAction -Execute "C:\Program Files\Prometheus\mysqld_exporter\mysqld_exporter.exe" -Argument '-config.my-cnf "C:\Program Files\Prometheus\mysqld_exporter\.my.cnf"'
$trigger =  New-ScheduledTaskTrigger -AtStartup 

Register-ScheduledTask -Action $action -Trigger $trigger -TaskName "MySQLd Exporter" -Description "Prometheus exporter for MySQL server metrics." -User "SYSTEM"
Enable-ScheduledTask -TaskName "MySQLd Exporter"
Start-ScheduledTask -TaskName "MySQLd Exporter" -AsJob

$Task = Get-ScheduledTask -TaskName "MySQLd Exporter"
$Task.Settings.ExecutionTimeLimit = "PT0S"
Set-ScheduledTask $Task
```

Thanks again @SuperQ!

**Comment by cdtinney** [comment]
I'd add that it can also be installed as a service via [NSSM](https://nssm.cc/download).

Make sure that you either add `DATA_SOURCE_NAME` as an environment variable when installing or that `.my.cnf` is in the same directory as the exporter executable. The service will not be able to access your home directory where the config file is located by default.
