### ISSUE TITLE
metrics collect problem when use  mysql_exporter to collect performance schema metrics

### ISSUE THREAD

**Issue by justlooks** [prometheus/mysqld_exporter#203]
the state of mysql endpoint is down and it says "server returned HTTP status 500 Internal Server Error" and i check the metrics, find the following error, anyone can tell me why?

> # curl http://172.16.20.7:9104/metrics
> 
> collected metric mysql_perf_schema_file_instances_total label:<name:"file_name" value:"db.opt" > label:<name:"mode" value:"read" > counter:<value:0 >  was collected before with the same name and label values

this is my start command

root       116     1  0 08:28 ?        00:00:01 /opt/mysqld_exporter-0.10.0.linux-amd64/mysqld_exporter -collect.binlog_size=true -collect.info_schema.processlist=true -collect.perf_schema.eventsstatements=true -collect.perf_schema.tableiowaits=true -collect.perf_schema.indexiowaits=true -collect.perf_schema.tablelocks=true -collect.perf_schema.eventswaits=true -collect.perf_schema.file_events=true -collect.perf_schema.file_instances=true

**Comment by SuperQ** [comment]
I suspect there is a problem with that collector.  For now I suggest you disable the file_instances collector.

If you could attach a copy of the query results for the file instances [query](https://github.com/prometheus/mysqld_exporter/blob/master/collector/perf_schema_file_instances.go#L15-L22) that would help.

**Comment by SuperQ** [comment]
Ok, I think I may see the issue with that collector.  It seems like the query/metric needs to include both the `FILE_NAME` and `EVENT_NAME` columns as labels in order to avoid duplication problems.

**Comment by SuperQ** [comment]
I found two issues with collector, PR to fix them out for review.

**Comment by justlooks** [comment]
that's means i need set both collect.perf_schema.file_instances.filter and collect.perf_schema.file_instances.remove_prefix ? but they both have default value

**Comment by SuperQ** [comment]
The file_instances filter default value is fine.  The main problem is the default for `remove_prefix` isn't safe for all use cases.  Setting `-collect.perf_schema.file_instances.remove_prefix=false` will help.

But there is still the issue that we are missing a label from the `EVENT_NAME` column.
