### ISSUE TITLE
How to disable collect.global_variables metric

### ISSUE THREAD

**Issue by lynch0227** [prometheus/mysqld_exporter#204]
Hi Guys,
  When I set collect.global_variables=false attribute, I still can see the related metric.
  How can I disable this flag?

Thank you.

**Comment by SuperQ** [comment]
That is the correct way to disable the feature.  How are you running the exporter?  Maybe there is a typo in your script?

**Comment by lynch0227** [comment]
@SuperQ 
Here is the command, is there any mistake?
./mysqld_exporter config.my-cnf=/usr/local/mysql_5728/my.cnf collect.global_variables=false collect.global_status=false

**Comment by SuperQ** [comment]
Your flags are missing `-` in front of them.  `-collect.global_variables=false`
