### ISSUE TITLE
Error pinging mysqld: dial tcp 127.0.0.1:9104

### ISSUE THREAD

**Issue by tsrinath1986** [prometheus/mysqld_exporter#207]
Hi,

when i am trying to run mysqld_exporter i am getting this error. followed the readme document for mysqld_exporter running.

=error msg="Error pinging mysqld: dial tcp 127.0.0.1:9104: getsockopt: connection refused" source="mysqld_exporter.go:268"

**Comment by SuperQ** [comment]
You have configured the exporter to use port 9104 instead of 3306.
