### ISSUE TITLE
mysql_exporter_last_scrape_error 0 when mysql_up is 0

### ISSUE THREAD

**Issue by guidoiaquinti** [prometheus/mysqld_exporter#216]
`mysql_exporter_last_scrape_error` is reporting 0 (success) also when `mysql_up` is 0 (down). 

This is a bit confusing if we rely on `mysql_exporter_last_scrape_error` to check for failures. 

Steps to reproduce:
- start `mysqld_exporter`
- saturate the connection pool of the MySQL user used
- `mysqld_exporter` will report: 
```
Jul 03 06:21:41 bash[14316]: time="2017-07-03T06:21:41-07:00" level=error msg="Error pinging mysqld: Error 1226: User 'monitoring_a' has exceeded the 'max_user_connections' resource (current value: 3)" source="mysqld_exporter.go:269"
```
while returning
```
mysql_exporter_last_scrape_error 0
mysql_up 0
mysql_exporter_scrapes_total 6716
```

**Comment by SuperQ** [comment]
Ahh, good catch.  Looking at the code, I'm not sure this `mysql_exporter_last_scrape_error` does anything at all. :grimacing: I can't find any point in the exporter where we use it.

**Comment by siavashs** [comment]
I can look into this.
Should we set this metric to **1** even if one of the correctors fail? Or is it for a general failures like connection issues with MySQL?

**Comment by SuperQ** [comment]
Any collector error should set this metric to 1.

**Comment by s4wet** [comment]
in my.cnf  add line
bind-address = 127.0.0.1
