### ISSUE TITLE
Available Downtime before SST Required not populating with ver 0.10.0

### ISSUE THREAD

**Issue by gravyflex** [prometheus/mysqld_exporter#218]
I am testing 0.10.0. I am seeing the gcache size information being populated. I am not seeing the data populating and I was wondering if there is some additional configuration that is required?

![image](https://user-images.githubusercontent.com/7466316/27933239-3b03a286-6266-11e7-8a02-454fb369091b.png)

![image](https://user-images.githubusercontent.com/7466316/27933257-50d5795e-6266-11e7-99dd-3b763c6c01fb.png)

**Comment by SuperQ** [comment]
Please post the queries you are using to generate these dashboards.

**Comment by SuperQ** [comment]
Without additional information there is nothing we can do here.
