### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by andrewhowdencom** [prometheus/mysqld_exporter#220]
Hola All, 

This is a request to cut a release. Running into the bug at #200 using the latest version (0.10.0); cutting a new release means uploading new binaries, which means I can consume them in ansible tasks. 

Much love <3

**Comment by andrewhowdencom** [comment]
Sweet! No rush that stuff isn't critical; just "hey this would be cool".

**Comment by SuperQ** [comment]
I think a nice update before PromCon in mid August would be good.

Any help squashing existing issues before then would be appreciated. 😉 ❤️

**Comment by julian-eggers** [comment]
Please cut a new release, I also need a fix for #200 ;-)

**Comment by AlekSi** [comment]
@SuperQ both #167 and #216 are closed now. Anything holding else holding the release?

**Comment by SuperQ** [comment]
Technically I wanted https://github.com/prometheus/mysqld_exporter/pull/259 to be the real fix for https://github.com/prometheus/mysqld_exporter/issues/167.

I've just merged it, but I've not had time to do any testing of the changes.  @AlekSi could you build and test a cut from master to make sure we don't have any show stopping issues?

**Comment by arvenil** [comment]
Just tested it. Found one issue https://github.com/prometheus/mysqld_exporter/pull/263 @SuperQ could you also update the `CHANGELOG`?

**Comment by AlekSi** [comment]
@SuperQ Can we help you with anything else?

**Comment by TheyDroppedMe** [comment]
Any word on when this will get cut?

**Comment by jhinklew** [comment]
We're also very interested in when this will happen

**Comment by TheyDroppedMe** [comment]
Is there anything holding this back from a release at this point?

**Comment by SuperQ** [comment]
Sorry, I've been traveling and haven't had the time to cut the release.  I will try and get to it soon.

**Comment by Juanchimienti** [comment]
Let us know if you need any help

**Comment by zoonage** [comment]
Does anything need to be done for a new release?

**Comment by andrewhowdencom** [comment]
WHOO!! :tada:
