### ISSUE TITLE
can't load package make: *** [format] Error 1

### ISSUE THREAD

**Issue by denglitong** [prometheus/mysqld_exporter#221]
[root@Mysql-master mysqld_exporter-master]# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build094540845=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

>[root@Mysql-master mysqld_exporter-master]# pwd
/root/mysqld_exporter/mysqld_exporter-master
[root@Mysql-master mysqld_exporter-master]# ll
total 92
-rw-r----- 1 root root  5733 Jul  6 01:54 CHANGELOG.md
-rw-r----- 1 root root  2395 Jul  6 01:54 circle.yml
drwxr-x--- 2 root root  4096 Jul  6 01:54 collector
-rw-r----- 1 root root   870 Jul  6 01:54 CONTRIBUTING.md
-rw-r----- 1 root root   222 Jul  6 01:54 Dockerfile
-rw-r----- 1 root root  3920 Jul  6 01:54 example.rules
-rw-r----- 1 root root 11325 Jul  6 01:54 LICENSE
-rw-r----- 1 root root    32 Jul  6 01:54 MAINTAINERS.md
-rw-r----- 1 root root  1822 Jul  6 01:54 Makefile
-rw-r----- 1 root root 20067 Jul  6 01:54 mysqld_exporter.go
-rw-r----- 1 root root  2465 Jul  6 01:54 mysqld_exporter_test.go
-rw-r----- 1 root root    65 Jul  6 01:54 NOTICE
-rw-r----- 1 root root  7806 Jul  6 01:54 README.md
drwxr-x--- 5 root root  4096 Jul  6 01:54 vendor
-rw-r----- 1 root root     7 Jul  6 01:54 VERSION
[root@Mysql-master mysqld_exporter-master]# make
>> formatting code
can't load package: package _/root/mysqld_exporter/mysqld_exporter-master: cannot find package "_/root/mysqld_exporter/mysqld_exporter-master" in any of:
        /usr/local/go/src/_/root/mysqld_exporter/mysqld_exporter-master (from $GOROOT)
        /root/go/src/_/root/mysqld_exporter/mysqld_exporter-master (from $GOPATH)
can't load package: package _/root/mysqld_exporter/mysqld_exporter-master/collector: cannot find package "_/root/mysqld_exporter/mysqld_exporter-master/collector" in any of:
        /usr/local/go/src/_/root/mysqld_exporter/mysqld_exporter-master/collector (from $GOROOT)
        /root/go/src/_/root/mysqld_exporter/mysqld_exporter-master/collector (from $GOPATH)
make: *** [format] Error 1

what's wrong? why when i make it notice to find the package which start with the letter '_', and why it's to find the package from $GOROOT $GOPATH, thanks much.

**Comment by denglitong** [comment]
go version go1.8.3 linux/amd64

**Comment by denglitong** [comment]
>> formatting code
can't load package: package \_/root/mysqld_exporter/mysqld_exporter-master: cannot find package "\_/root/mysqld_exporter/mysqld_exporter-master" in any of:
        /usr/local/go/src/\_/root/mysqld_exporter/mysqld_exporter-master (from $GOROOT)
        /root/go/src/\_/root/mysqld_exporter/mysqld_exporter-master (from $GOPATH)
can't load package: package _/root/mysqld_exporter/mysqld_exporter-master/collector: cannot find package "_/root/mysqld_exporter/mysqld_exporter-master/collector" in any of:
        /usr/local/go/src/_/root/mysqld_exporter/mysqld_exporter-master/collector (from $GOROOT)
        /root/go/src/\_/root/mysqld_exporter/mysqld_exporter-master/collector (from $GOPATH)

**Comment by SuperQ** [comment]
Your `GOPATH` is not setup correctly.  You need to build from within the correct `GOPATH`.  For you the directory needs to be `/root/go/src/github.com/prometheus/mysqld_exporter`.

**Comment by denglitong** [comment]
Oh yeah, you are right! stupid am i, thanks muck!
