### ISSUE TITLE
Integration testing with Docker Compose

### ISSUE THREAD

**Issue by AlekSi** [prometheus/mysqld_exporter#223]
Are you interested in adding Docker Compose configuration for integration testing? That way Travis CI can run tests with different versions of MySQL, and everyone can be able to do the same locally.

**Comment by SuperQ** [comment]
That could be interesting.  We're also looking into using buildkite for another project (`node_exporter`) to support non-Linux-x64 platforms.

**Comment by AlekSi** [comment]
See #228.
