### ISSUE TITLE
How to solve mysql_up is 0

### ISSUE THREAD

**Issue by caipengtao** [prometheus/mysqld_exporter#224]
The Targets is UP...
![d75ecf14-fdb0-4b49-a721-3ad262f7c75a](https://user-images.githubusercontent.com/19907364/29447921-be07da62-8426-11e7-920a-060eb1ff305a.png)
and I see some links in the mysql to select information_schema.tables . But the prometheus collect nothing, how to solve it?   thanks

**Comment by SuperQ** [comment]
Please direct usage questions to our [community](https://prometheus.io/community/).

I would suggest examining the exporter logs.
