### ISSUE TITLE
`make` error

### ISSUE THREAD

**Issue by rnkhouse** [prometheus/mysqld_exporter#227]
When I run make in the source code directory:

>> formatting code
can't load package: package _/opt/prometheus_exporters/mysqld_exporter: cannot find package "_/opt/prometheus_exporters/mysqld_exporter" in any of:
        /usr/lib/go/src/pkg/_/opt/prometheus_exporters/mysqld_exporter (from $GOROOT)
        /root/go/src/_/opt/prometheus_exporters/mysqld_exporter (from $GOPATH)
can't load package: package _/opt/prometheus_exporters/mysqld_exporter/collector: cannot find package "_/opt/prometheus_exporters/mysqld_exporter/collector" in any of:
        /usr/lib/go/src/pkg/_/opt/prometheus_exporters/mysqld_exporter/collector (from $GOROOT)
        /root/go/src/_/opt/prometheus_exporters/mysqld_exporter/collector (from $GOPATH)
make: *** [format] Error 1

**Comment by matthiasr** [comment]
Go is particular about the layout of your repositories. Try

```
mkdir -p "${GOPATH}/github.com/prometheus"
mv /opt/prometheus_exporters/mysqld_exporter "${GOPATH}/github.com/prometheus/myswld_exporter"
```

**Comment by rfrail3** [comment]
A workaround is directly with:
`go get github.com/prometheus/mysqld_exporter`
