### ISSUE TITLE
Getting Error While connecting remote machine mysqld

### ISSUE THREAD

**Issue by manikSMahajan** [prometheus/mysqld_exporter#231]
This is data source i set =  export DATA_SOURCE_NAME='exporter:password@alef:alef@123@192.168.0.218(/var/run/mysqld/mysqld.sock)/'
which gives me this error.
mmahajan@DEV-MMahajan:~/Prometheus/mysqld_exporter$ ./mysqld_exporter 
INFO[0000] Starting mysqld_exporter (version=0.10.0, branch=master, revision=8285b298c04c40282dbeb46a0f59abb554a87810)  source="mysqld_exporter.go:181"
INFO[0000] Build context (go=go1.7.6, user=mmahajan@DEV-MMahajan, date=20170906-09:51:27)  source="mysqld_exporter.go:182"
ERRO[0000] Error pinging mysqld: dial 192.168.0.218: unknown network 192.168.0.218  source="exporter.go:162"
INFO[0000] Listening on :9104                            source="mysqld_exporter.go:229"
ERRO[0006] Error pinging mysqld: dial 192.168.0.218: unknown network 192.168.0.218  source="exporter.go:162"

**Comment by SuperQ** [comment]
The format of your DSN is invalid.  Please refer to the [documentation](https://github.com/prometheus/mysqld_exporter#running).

For future reference, please use our [community support](https://prometheus.io/community/) contacts for help with usage.

**Comment by manikSMahajan** [comment]
Yes.. I solved it DSN was wrong .. It should be ,
DATA_SOURCE_NAME='exporter:password@(192.168.0.218)'
