### ISSUE TITLE
With what version would I see a mysql_slave_status_sql_delay metric?

### ISSUE THREAD

**Issue by wtip** [prometheus/mysqld_exporter#239]
In the example.rules file there's a reference to a `mysql_slave_status_sql_delay` metric. I don't seem to see this metric on any of my exporters. Does this only show up on certain mysql versions?

**Comment by SuperQ** [comment]
SQL delay was introduced in [MySQL 5.6](https://dev.mysql.com/doc/refman/5.6/en/replication-delayed.html).

**Comment by wtip** [comment]
Thanks!
Since all of the clusters that I'm monitoring are running mysql 5.5 this explains why I'm not seeing it.
