### ISSUE TITLE
level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"

### ISSUE THREAD

**Issue by Murryy79** [prometheus/mysqld_exporter#240]
Hello:
I noticed mysql dashboards has no data to show in grafana. 
![image](https://user-images.githubusercontent.com/19574664/31999901-80d684a4-b95a-11e7-900f-22105a121e46.png)

Upon investigating, I peeked into /var/vcap/sys/log/mysqld_exporter/mysqld_exporter.stderr.log and found bunch of these error messages
time="2017-10-20T22:04:36Z" level=info msg="Starting mysqld_exporter (version=0.10.0, branch=master, revision=80680068f15474f87847c8ee8f18a2939a26196a)" source="mysqld_exporter.go:460"
time="2017-10-20T22:04:36Z" level=info msg="Build context (go=go1.8.1, user=root@3b0154cd9e8e, date=20170425-11:24:12)" source="mysqld_exporter.go:461"
time="2017-10-20T22:04:36Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:04:36Z" level=info msg="Listening on :9104" source="mysqld_exporter.go:479"
time="2017-10-20T22:10:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:11:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:12:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:13:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:14:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:15:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:16:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:17:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"
time="2017-10-20T22:18:23Z" level=error msg="Error pinging mysqld: dial tcp: lookup ((mysqld_exporter.mysql.address)): no such host" source="mysqld_exporter.go:268"

how do i get this host mysqld_exporter.mysql.address to resolve or fix these errors and eventually populate sql dashboards
regards
Murry

**Comment by SuperQ** [comment]
This is a problem with your configuration, and not a bug in the `mysqld_exporter`.  It looks like you're using a pre-built cloudfoundry configuration, I suggest contacting their support.

**Comment by Murryy79** [comment]
@SuperQ  Thanks for your quick response. 
Since you seem to know what the issue is with configuration, can you help with which configuration and where to look for it?

I did not understand pre-built cloudfoundry configuration. I am actually using instructions from here https://github.com/pivotal-cf/prometheus-on-PCF is that you meant?

**Comment by SuperQ** [comment]
I have no idea what the issue with the configuration is, as I am completely unfamiliar with cloudfoundry's setup.  I simply googled `vcap` to figure out where the config came from.

I suggest you file an issue with Pivotal, as this is a problem with their code.

**Comment by SuperQ** [comment]
Another option would be to post your question on our [community](https://prometheus.io/community/).

**Comment by AashishChughHome** [comment]
Facing same issue.
