### ISSUE TITLE
Add examples rules file in 2.0 yaml format

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/mysqld_exporter#246]
The current example file is in the 1.8 alert file format, it would be nice to provide an example in the new yaml format.

https://github.com/prometheus/mysqld_exporter/blob/master/example.rules

**Comment by Techcadia** [comment]
Here is the PR
https://github.com/prometheus/mysqld_exporter/pull/248

I ran the convert

**Comment by SuperQ** [comment]
Closed with #248
