### ISSUE TITLE
Errors in the logs when using MySQL 5.7

### ISSUE THREAD

**Issue by ThomWright** [prometheus/mysqld_exporter#249]
### Host operating system: output of `uname -a`

`Linux af4039cf083e 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 GNU/Linux` (the Docker container)

### mysqld_exporter version: output of `mysqld_exporter --version`

```
mysqld_exporter, version 0.10.0 (branch: master, revision: 80680068f15474f87847c8ee8f18a2939a26196a)
  build user:       root@3b0154cd9e8e
  build date:       20170425-11:24:12
  go version:       go1.8.1
```

### MySQL server version

Before: latest 5.6
Now: latest 5.7

### mysqld_exporter command line flags

```
"-collect.binlog_size=true",
"-collect.info_schema.processlist=true",
"-collect.info_schema.tablestats=true",
"-collect.info_schema.query_response_time=true",
"-collect.perf_schema.eventsstatements=true",
"-collect.perf_schema.eventswaits=true",
"-collect.perf_schema.file_events=true",
"-collect.perf_schema.indexiowaits=true",
"-collect.perf_schema.tableiowaits=true",
"-collect.perf_schema.tablelocks=true",
```

### What did you do that produced an error?

Updated MySQL from the latest 5.6 Docker image (`mysql:5.6`) to the latest 5.7 Docker image (`mysql:5.7`).

### What did you expect to see?

No errors in the logs (I'm fairly sure there were none when using 5.6)

### What did you see instead?

```
mysql-metrics_1     | time="2017-12-07T15:03:35Z" level=error msg="Error scraping for collect.perf_schema.eventsstatements: Error 1055: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'Q.DIGEST_TEXT' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" source="mysqld_exporter.go:359" 
```

**Comment by SuperQ** [comment]
This is fixed in master, but not in the current release.

Duplicate: https://github.com/prometheus/mysqld_exporter/issues/200
