### ISSUE TITLE
How to monitor locally installed mysql server using mysqld_exporter

### ISSUE THREAD

**Issue by roshu10** [prometheus/mysqld_exporter#260]
Syntax for monitoring mysq using this exporter is

docker run -d -p 9104:9104 --link=my_mysql_container:bdd  \
        -e DATA_SOURCE_NAME="user:password@(bdd:3306)/database" prom/mysqld-exporter

However, I have installed mysql on my local machine and running mysqld_exporter as a container.

Then what will be the syntax for collecting the metrics from there ? (what's the value for --link=my_mysql_container:bdd and datasource name)

Thanks for any help :)

**Comment by SuperQ** [comment]
This seems like a Docker configuration problem.  I suggest asking on the [Prometheus community](https://prometheus.io/community/) as github issues are reserved for filing bugs/feature requests.
