### ISSUE TITLE
Add support for group replication metrics

### ISSUE THREAD

**Issue by ezraroi** [prometheus/mysqld_exporter#266]
Currently none of the group replication performance metrics are being exported.

performance_schema.replication_group_member_stats
performance_schema.replication_group_members

**Comment by First-Met** [comment]
Looking forward to add monitoring mysqld_exporter for MySQL Group Replication!

**Comment by ezraroi** [comment]
started working on it.. will open a PR next week

**Comment by dimgsg9** [comment]
Hi guys, just wondering how is it going? We are actively using GR in production, @ezraroi - if any helps is needed - pls let me know...

**Comment by ezraroi** [comment]
i opened a PR 30 days ago

**Comment by SuperQ** [comment]
Yes, sorry I took so long getting back to the review.

**Comment by ezraroi** [comment]
fixed by #271

**Comment by ezraroi** [comment]
@SuperQ  any date for next release of the exporter?

**Comment by SuperQ** [comment]
I'll start preparing one this week while I'm at KubeCon.

**Comment by ezraroi** [comment]
@SuperQ any update on the release?
