### ISSUE TITLE
Startup and queries slow

### ISSUE THREAD

**Issue by RubenHoms** [prometheus/mysqld_exporter#268]
### Host operating system: output of `uname -a`
`Linux db0-staging 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux` (Debian jessie 8.10)

### mysqld_exporter version: output of `mysqld_exporter --version`
```
mysqld_exporter, version 0.10.0 (branch: master, revision: 80680068f15474f87847c8ee8f18a2939a26196a)
  build user:       root@3b0154cd9e8e
  build date:       20170425-11:24:12
  go version:       go1.8.1
```
### MySQL server version
```
mysql> SELECT VERSION();
+------------------+
| VERSION()        |
+------------------+
| 5.5.59-38.11-log |
+------------------+
1 row in set (0.00 sec)
```

### mysqld_exporter command line flags
```--config.my-cnf=/root/.my.cnf```

I have 2 seperate issues but think they might be connected to one another.

I have a MySQL instance (Percona) with one database, with ~300 tables. I've setup the `mysqld_exporter` on my system but when I run it it takes around 2 minutes for the process to start listening on its port. Here's some output that proves this:
```
Feb 21 14:41:21 db0-staging mysqld_exporter[30856]: time="2018-02-21T14:41:21+01:00" level=info msg="Starting mysqld_exporter (version=0.10.0, branch=master, revision=80680068f15474f87847c8ee8f18a2939a26196a)" source="mysqld_exporter.go:460"
Feb 21 14:41:21 db0-staging mysqld_exporter[30856]: time="2018-02-21T14:41:21+01:00" level=info msg="Build context (go=go1.8.1, user=root@3b0154cd9e8e, date=20170425-11:24:12)" source="mysqld_exporter.go:461"
Feb 21 14:43:29 db0-staging mysqld_exporter[30856]: time="2018-02-21T14:43:29+01:00" level=info msg="Listening on :9104" source="mysqld_exporter.go:479"
```
I don't have a lot of databases/tables so I'm not sure what would happen if it was a bigger setup but this looks similar to what #261 is experiencing.

The second part to this issue is the response time for the metrics. It can take up to 3 minutes for a request to `/metrics` to return a response. This does not seem like a reasonable amount of time for a response to come back. Especially if the default Prometheus scraping timeout is 15 seconds. Here's some output to show this in action:
```
root@mydb:/root# time curl localhost:9104/metrics
-- removed output to save some space ----
real	2m7.496s
user	0m0.008s
sys	0m0.008s
```
During this time if I inspect the MySQL/exporter process with `top` or `iotop` it doesn't seem to be doing much either.

**Comment by RubenHoms** [comment]
I just tried the same with an older release (0.9.0) but the same problem persists.

**Comment by SuperQ** [comment]
Can you `strace` this slow startup?  It would be useful to see what is going on.

**Comment by RubenHoms** [comment]
I found out what was causing this, and it turns out it was unrelated to your awesome project. (great work btw!) 

I have an IPv6 enabled server on which `localhost` resolves to `::1`. But my firewall blocks these requests with a `-j DROP`. Because of this it then times out after 2 minutes and starts trying `127.0.0.1`, which is not blocked. This explains why it takes 2 minutes and a few seconds for both the server to come up as well as the metrics to come back.

Keep up the good work and sorry to waste your time ;)

**Comment by SuperQ** [comment]
Oh! Very nice debugging.  Glad it's resolved.
