### ISSUE TITLE
Support TRUNCATE TABLE for performance_schema tables

### ISSUE THREAD

**Issue by SuperQ** [prometheus/mysqld_exporter#27]
For `performance_schema.events_statements_summary_by_digest`, we limit the number of metrics we extract by using `ORDER BY SUM_TIMER_WAIT DESC LIMIT ?`.  This can cause some queries that were active at one time in the past to stay at the top of the list.

We should provide a feature to `TRUNCATE TABLE` on a periodic basis to keep the list up to date with current use patterns.

**Comment by brian-brazil** [comment]
Truncate is an administrative action, I'd argue that has no place in a monitoring tool and that that should be done outside of the exporter.

**Comment by SuperQ** [comment]
I thought about that, but the reason I'm thinking about having it as part of the exporter is along the lines of "do the right thing all from one place".

Maybe instead of being directly in the mysqld_exporter, we could make it a stand alone tool and recommend how to use it.

Since the duration between truncates could be on the order of hours, a bash cron job should be good enough.

**Comment by matthiasr** [comment]
I'm with @brian-brazil here, this should be outside. If we want to limit the exporter to recent events, we should adapt the query, e.g. `WHERE last_seen < DATE_SUB(NOW(), INTERVAL 1 HOUR) ORDER BY SUM_TIMER_WAIT DESC LIMIT ?`.

The exporter should function whether the user wants to remove the events or not; they may be needed elsewhere too.

**Comment by SuperQ** [comment]
Hrm, that's probably a better patch.

**Comment by SuperQ** [comment]
No, that patch would still not give us what we want.  Even with `last_seen`, a low use query that may have had high usage in the past would dominate the current metrics.  With Prometheus, we no longer need the counters past a reasonable time range, since it will still remember the historical values for us as timeseries.

**Comment by matthiasr** [comment]
Then we need to either express exactly the logic we want in the query, or process the events in the exporter – but relying on truncation of the table to get the data we want is brittle and unpredictable.

**Comment by SuperQ** [comment]
It's not unpredictable, it's actually quite predictable and reasonable when you do regular counter resets.  The whole reason we have Prometheus is so that it remembers the previous digest data.  The only reason we have to do a little bit of these hoops is because for some use cases, the amount of data is more than Prometheus can currently handle.

**Comment by SuperQ** [comment]
I've added a conservative patch PR to only collect metrics for query digests that have been used in the last day.  (to allow for daily cron jobs to stay in the collection cycle)

https://github.com/prometheus/mysqld_exporter/pull/28

**Comment by SuperQ** [comment]
Merged #28, Should be good enough.
