### ISSUE TITLE
Error pinging mysqld

### ISSUE THREAD

**Issue by RobiD** [prometheus/mysqld_exporter#278]
Hi,

We followed the instructions [here](https://github.com/prometheus/mysqld_exporter) in order to setup monitoring for our MySQL Database as part of PCF. However, when trying to run the Exporter, we are getting the following error:
```
ERRO[0000] Error pinging mysqld: Error 1045: Access denied for user 'mysqld_exporter'@'{{IP_ADDRESS}}' (using password: YES) source="mysqld_exporter.go:268"
```

Any suggestions on how to resolve that?

`mysqld_exporter version: v0.10.0`
`MySQL for PCF: v1.10.8`

It is related to this ticket [#174](https://github.com/prometheus/mysqld_exporter/issues/174), but no real solution has been proposed.

Thanks!

**Comment by SuperQ** [comment]
For help and other usage questions, please use our [community](https://prometheus.io/community/). Github issues are reserved for bug reports and feature requests. There are not enough maintainers to answer all questions.

**Comment by aggronmagi** [comment]
my password contain '#'

https://alexkunin.medium.com/prometheus-mysqld-exporter-and-access-denied-errors-8e4d3e54f0af

Did some googling, and here is incomplete list of possible reasons:
 1. quotes around values in config files (this is probably specifc to Ansible)
 2. funny characters in password: %, #, etc.
 3. invalid user host
