### ISSUE TITLE
system charts missing,others is ok

### ISSUE THREAD

**Issue by willwee** [prometheus/mysqld_exporter#284]
### Host operating system: output of `uname -a`
install in docker,docker version below:
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

### mysqld_exporter version: output of `mysqld_exporter --version`

v0.10.0
### MySQL server version
mysql     verison:5.7.18-log
### mysqld_exporter command line flags

default
### What did you do that produced an error?

<img width="1228" alt="qq20180522-150008 2x" src="https://user-images.githubusercontent.com/7963299/40346964-1ce2b6a4-5dd1-11e8-8626-604b972c62c0.png">

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/).  There are many more people there that can help.  GitHub issues are reserved for bug reports and feature requests.
