### ISSUE TITLE
Error pinging mysqld: this authentication plugin is not supported

### ISSUE THREAD

**Issue by sunhongtao** [prometheus/mysqld_exporter#285]
### Host operating system: output of `uname -a`
Darwin MacBook-Pro-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
### mysqld_exporter version: output of `mysqld_exporter --version`

/ # mysqld_exporter --version
mysqld_exporter, version 0.10.0 (branch: master, revision: 80680068f15474f87847c8ee8f18a2939a26196a)
  build user:       root@3b0154cd9e8e
  build date:       20170425-11:24:12
  go version:       go1.8.1

### MySQL server version
mysql  Ver 8.0.11 for Linux on x86_64 (MySQL Community Server - GPL)
### mysqld_exporter command line flags

docker run -d -p 9140:9140 -e DATA_SOURCE_NAME='XXXX:XXXX@(X.X.X.X:3306)/' prom/mysqld-exporter
### What did you do that produced an error?
 docker logs -f d74
time="2018-05-23T09:48:47Z" level=info msg="Starting mysqld_exporter (version=0.10.0, branch=master, revision=80680068f15474f87847c8ee8f18a2939a26196a)" source="mysqld_exporter.go:460" 
time="2018-05-23T09:48:47Z" level=info msg="Build context (go=go1.8.1, user=root@3b0154cd9e8e, date=20170425-11:24:12)" source="mysqld_exporter.go:461" 
time="2018-05-23T09:48:47Z" level=error msg="Error pinging mysqld: this authentication plugin is not supported" source="mysqld_exporter.go:268" 
time="2018-05-23T09:48:47Z" level=info msg="Listening on :9104" source="mysqld_exporter.go:479"

**Comment by SuperQ** [comment]
That error is coming from the go SQL driver, it seems to indicate that the connection is being rejected by the MySQL server.  Possibly you have an invalid character in the DSN string.

**Comment by sunhongtao** [comment]
After I changed the mysql version to 5.7,the problem was solved.Thank You.

**Comment by count0ru** [comment]
You need to run mysqld with ```--default_authentication_plugin=mysql_native_password``` and create user for mysqld_exporter: ```CREATE 'exporter'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY 'yoursecretpassword';```
