### ISSUE TITLE
Activating  metrics: What flags are necessary to enable some MySQL advanced metrics?

### ISSUE THREAD

**Issue by gustavodescs** [prometheus/mysqld_exporter#289]
### mysqld_exporter version: mysqld_exporter, version 0.10.0 (branch: master, revision: 80680068f15474f87847c8ee8f18a2939a26196a)
  build user:       root@3b0154cd9e8e
  build date:       20170425-11:24:12
  go version:       go1.8.1

### mysqld_exporter command line flags: /opt/exporter/bin/mysqld_exporter -collect.binlog_size -collect.info_schema.processlist -collect.engine_innodb_status -collect.info_schema.innodb_metrics -collect.info_schema.innodb_tablespaces -collect.info_schema.userstats -collect.perf_schema.eventsstatements -collect.perf_schema.indexiowaits -collect.perf_schema.tableiowaits

I'd like to know what are the necessary flags I need to activate in order to enable some specific/advanced metris on mysql monitoring using "MySQL InnoDB Metrics Advanced" template from Percona. Below, i will list some example of metrics used by this one:

mysql_info_schema_innodb_metrics_index_index_page_merge_attempts_total, mysql_info_schema_innodb_metrics_index_index_page_merge_successful_total, mysql_info_schema_innodb_metrics_index_index_page_splits_total, mysql_info_schema_innodb_metrics_index_index_page_merge_successful_total, mysql_info_schema_innodb_metrics_recovery_log_lsn_current
mysql_info_schema_innodb_metrics_index_index_page_reorg_successful_total,
mysql_info_schema_innodb_metrics_index_index_page_reorg_attempts_total,, mysql_info_schema_innodb_metrics_lock_lock_rec_lock_created_total,
mysql_info_schema_innodb_metrics_lock_lock_rec_lock_removed_total,
mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total,
(....)

Thank you

**Comment by SuperQ** [comment]
It sounds like this is some extra functionality provided by Percona's fork of this exporter.

**Comment by delgod** [comment]
@gustavodescs, please try tune MySQL according to https://www.percona.com/doc/percona-monitoring-and-management/conf-mysql.html

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/).  There are many more people there that can help.  GitHub issues are reserved for bug reports and feature requests.
