### ISSUE TITLE
Userstats broken

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/mysqld_exporter#29]
This refactoring https://github.com/prometheus/mysqld_exporter/commit/58de609465439a1074306db1299cad7dcec0c23c#diff-7f3e92469561ad831b3efc026d4ffcddR875  broke the fix done just earlier https://github.com/prometheus/mysqld_exporter/commit/dbad3dcf71d5eb6a659aaacf4fb86253b9da15a5

Should be
```
-               userStatScanArgs[i+1] = &userStatData[i+1]
+               userStatScanArgs[i+1] = &userStatData[i]
```

**Comment by juliusv** [comment]
@SuperQ

**Comment by SuperQ** [comment]
Yup, was just making a PR for it now.

**Comment by roman-vynar** [comment]
Thanks!
