### ISSUE TITLE
make is failing

### ISSUE THREAD

**Issue by haribole** [prometheus/mysqld_exporter#290]
### Host operating system: output of `uname -a`
Linux prom 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you see instead?

vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15: unknown assembly argument type syscall.Errno
vendor/golang.org/x/sys/unix/asm_linux_amd64.s:16: [amd64] Syscall: function Syscall missing Go declaration
vendor/golang.org/x/sys/unix/asm_linux_amd64.s:19: [amd64] Syscall6: function Syscall6 missing Go declaration
vendor/golang.org/x/sys/unix/asm_linux_amd64.s:37: [amd64] RawSyscall: function RawSyscall missing Go declaration
vendor/golang.org/x/sys/unix/asm_linux_amd64.s:40: [amd64] RawSyscall6: function RawSyscall6 missing Go declaration
vendor/golang.org/x/sys/unix/asm_linux_amd64.s:56: [amd64] gettimeofday: function gettimeofday missing Go declaration
exit status 1
Makefile.common:69: recipe for target 'vet' failed
make: *** [vet] Error 1

**Comment by SuperQ** [comment]
What version of Go are you building with?

**Comment by SuperQ** [comment]
I am unable to reproduce this. My only guess is that this is coming from an old or misconfigure Go compiler. The current release passes a full build and test via our CI pipeline.

Without additional information there is nothing we can do.
