### ISSUE TITLE
how to use this exporter

### ISSUE THREAD

**Issue by 13567436138** [prometheus/mysqld_exporter#293]
do i need to startup one exporter contianer for each mysql server?I have sevarla my sql server.

**Comment by SuperQ** [comment]
Yes, exporters are designed to be deployed 1:1 with their targets. This avoids a number of problems with identity and SPoF.

For usage questions/help, please use our [community](https://prometheus.io/community/).  There are many more people there that can help.  GitHub issues are reserved for bug reports and feature requests.
