### ISSUE TITLE
Information about calculation interval and possibly make it configurable

### ISSUE THREAD

**Issue by tom932** [prometheus/mysqld_exporter#305]
### Host operating system

official docker container from dockerhub

### mysqld_exporter version

v0.11.0

### mysqld_exporter command line flags

Default command line flags, since official docker version

### Feature request

Currently, the Readme.md doesn't state, how often the data is calculated, and therefore, which scrape interval for prometheus makes sense. It would be nice if that information is added.

Furthermore, it would be nice to be able to configure how often data is calculated by the exporter. For some people, it would be sufficient to get updated data every 5 minutes, if only little disk space for prometheus is avalailable or db traffic should be minimized for busy instances. For others 10s might be useful to get more exact data.

Therefore, a new General flag would make sense to configure the calcuation interval.

**Comment by SuperQ** [comment]
Data is collected on demand when Prometheus scrapes. There are no calculations.

15 seconds is a typical scrape interval.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
