### ISSUE TITLE
MySQL 8 Support?

### ISSUE THREAD

**Issue by aliensmily** [prometheus/mysqld_exporter#308]
### Host operating system: output of `uname -a`
Linux gisu665 4.4.131-94.29-default #1 SMP Mon May 21 14:41:34 UTC 2018 (f49bc78) x86_64 x86_64 x86_64 GNU/Linux
=> SLES12

### mysqld_exporter version: output of `mysqld_exporter --version`
mysqld_exporter, version 0.11.0 (branch: HEAD, revision: 5d7179615695a61ecc3b5bf90a2a7c76a9592cdd)
  build user:       root@3d3ff666b0e4
  build date:       20180629-15:00:35
  go version:       go1.10.3

### MySQL server version
MySQL 8.0.11

### mysqld_exporter command line flags
/opt/mysql/product/exporters/mysqld_exporter --config.my-cnf="/home/mysqladm/.my.cnf"

### What did you do that produced an error?
Starting the exporter targeting a MySQL 8+ database.

### What did you expect to see?
Working MySQL endpoint in Prometheus

### What did you see instead?
Prometheus journal:
`Jul 25 15:00:42 host1 prometheus[21940]: level=warn ts=2018-07-25T13:00:42.153281006Z caller=scrape.go:713 component="scrape manager" scrape_pool=mysql target="http://some.host:9104/metrics?target=some.host%3A9104" msg="append failed" err="no token found"`

promtool check:
```
root@host1:/data/prometheus/bin# curl -s http://some.host:9104/metrics | ./promtool check metrics
error while linting: text format parsing error in line 893: invalid metric name in comment
```

=> Lines are:

```
# HELP mysql_global_status_validate_password.dictionary_file_words_count Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_validate_password.dictionary_file_words_count untyped
mysql_global_status_validate_password.dictionary_file_words_count 0
```

So i guess, there is actually no MySQL 8+ Support?

**Comment by SuperQ** [comment]
This is already being worked on :smile: 

See: https://github.com/prometheus/mysqld_exporter/pull/307

**Comment by aliensmily** [comment]
great! :+1: 

Thanks for the execellent community work (to all of the Prometheus project)! :)

**Comment by ChristianSchuit** [comment]
For those (like me) who cannot wait for a new release, a simple workaround is to set up an Apache HTTP server with PHP on the same machine, have it listen to port 9105 and place the following simple PHP script in `/var/www/html/metrics/index.php`:

```
<?php
header('Content-Type:text/plain; charset=UTF-8');
$url='http://127.0.0.1:9104/metrics';
$lines_array=file($url);
foreach ($lines_array as $index => $value) {
    if (stristr($value, 'dictionary_file_words_count') === FALSE
        && stristr($value, 'check_user_name') === FALSE
        && stristr($value, 'mysql_global_variables_validate_password') === FALSE) {
        print($value);
    }
}
?>
```

Then change the Prometheus configuration to scrape port 9105 instead of 9104.

Works like a charm.. :)
