### ISSUE TITLE
Described GRANT in docs is too permissive

### ISSUE THREAD

**Issue by augmenter** [prometheus/mysqld_exporter#311]
Hi,

Is it possible to write the specific SQL grant for the exporter user so that it is less permissive? The grant has a read permission to all the tables, and since the exporter is visible to prometheus - and prometheus itself is really hard to limit access to (prometheus webadmin), wouldn't it be better if the MYSQL user for this exporter would have just the needed stats from MYSQL and not a read option on the tables as well ?
I'm having a hard time coming up with the right combination of permissions to achieve this, or I would have posted a solution already.

**Comment by SuperQ** [comment]
Unfortunately, no. This is a limitation of MySQL. 😢 MySQL has no way to allow access to `information_schema` without granting everything.

The upside is that the exporter itself is very safe. It does not allow arbitrary query execution. There is no way to inject SQL attacks. So the information exposed by the exporter is exactly what you would expect.

It is possible to reduce the access grant to the exporter, but you would have to disable a number of features for this to work. I haven't experimented with this myself, so if you do end up coming up with a more secure grant and feature flag combo, it would be useful to document the tradeoff.

**Comment by augmenter** [comment]
Thank you for taking your time from your busy schedule to answer this! I really appreciate it :)
I'm really wary of the fact that prometheus has to be exposed publicly for grafana to work (grafana should route these calls on the internal network to prometheus), and just a few weeks ago I was able to google "prometheus admin" and stumbled on a lot of publicly exposed prometheus admins of some companies. And to make things worse, the prometheus has all targets listed, so you can easily go and find on which domain mysqld_export is running. Hope this helps you understand where I'm coming from and that I did not ask this without a justification :). 
Currently I have mysqnd_exporter on a local network and its not exposed to the internet, but you're right, prometheus cant inject calls to this exporter.
Thanks again!

**Comment by SuperQ** [comment]
Grafana can proxy query requests, it's in the datasource settings. There's no need to publicly expose Prometheus directly.
