### ISSUE TITLE
How to get the status if mysql is up or not?

### ISSUE THREAD

**Issue by AashishChughHome** [prometheus/mysqld_exporter#314]
I am trying to monitor my rds url from the exporter.

i close my rds still in metrics showing mysql is up how to make sure from metrics mysql database is up or not?

**Comment by SuperQ** [comment]
There is a `mysql_up` metric exposed by the exporter.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by AashishChughHome** [comment]
I am getting the error while executing docker command.
Surprise what is the reason of this.

![screenshot from 2018-08-03 18-54-13](https://user-images.githubusercontent.com/29576872/43645158-bac1fc3e-974e-11e8-95fa-7217e8b7d6b9.png)

**Comment by AashishChughHome** [comment]
I am using below command to start container.

docker run -d \
  -p 9104:9104 \
  --network my-mysql-network  \
  -e DATA_SOURCE_NAME="username:Password@(Db_url:3306)/" \
  prom/mysqld-exporter

**Comment by SuperQ** [comment]
This appears to be a firewall or configuration problem. Please verify that your settings are correct.
