### ISSUE TITLE
adding lock_wait_timeout to the default DNS breaks MySQL < 5.5.3

### ISSUE THREAD

**Issue by jcross-linkup** [prometheus/mysqld_exporter#316]
On connect I receive the error:
"Error pinging mysqld: Error 1193: Unknown system variable 'lock_wait_timeout'" source="exporter.go:76"

That is against MariaDB 5.1.47.  The variable lock_wait_timeout was added to MySQL in version 5.5.3:
https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_lock_wait_timeout

Making it part of the default DSN means that it won't work with MySQL / MariaDB versions below 5.5.3:
 https://github.com/prometheus/mysqld_exporter/blob/6b4e3df7f9fd9f4d92d519c3062a1eba9a225b8e/collector/exporter.go#L61

I tried collecting that variable from a session from a newer version of MariaDB as well as the older 5.1.47:
Server version: 10.0.35-MariaDB MariaDB Server
MariaDB [(none)]> show variables like '%lock_wait_timeout';
+--------------------------+----------+
| Variable_name            | Value    |
+--------------------------+----------+
| innodb_lock_wait_timeout | 50       |
| lock_wait_timeout        | 31536000 |
+--------------------------+----------+

Server version: 5.1.47-MariaDB (MariaDB - http://mariadb.com/)
MariaDB [(none)]> show variables like '%lock_wait_timeout';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| innodb_lock_wait_timeout | 3600  |
| table_lock_wait_timeout  | 50    |
+--------------------------+-------+

So it does indeed appear that 5.1.47 does not have variable.

It would be nice if that variable was removed from the DSN by default, or if it was configurable to not add it.

**Comment by SuperQ** [comment]
MySQL 5.1 has been EOL for almost 5 years. We will be dropping explicit support for it from this exporter soon[0]. MariaDB 5.1 has been EOL for over 3 years[1].

[0]: https://github.com/prometheus/mysqld_exporter/issues/298
[1]: https://mariadb.org/about/maintenance-policy/

**Comment by jcross-linkup** [comment]
Then please update README.md to explicitly state that MySQL >= 5.5.3 is supported.  Currently README.md lists MySQL >= 5.1 is supported, but it does not work with 5.1.  That will save time for people like me that are trying to figure out why a connection cannot be made MySQL < 5.5.3.

**Comment by SuperQ** [comment]
Yes, I am planning to do this.
