### ISSUE TITLE
Add minimal MySQL version to Scraper interface

### ISSUE THREAD

**Issue by AlekSi** [prometheus/mysqld_exporter#327]
@arvenil's PR #265 introduced `Scraper` interface. Now we propose to expand it to include the following method:
```go
type Scraper interface {
	// Version of MySQL from which scraper is available.
	Version() float64
}
```

It then can be used to skip unsupported versions entirely:

```go
	for _, scraper := range e.scrapers {
		if versionNum < scraper.Version() {
			continue
		}
```

I can work on porting this feature from Percona's fork if you are interested.

**Comment by SuperQ** [comment]
Oh, that sounds great.
