### ISSUE TITLE
how to collect multiple mysql instances metrics use mysqld_exporter

### ISSUE THREAD

**Issue by wangsz05** [prometheus/mysqld_exporter#344]
HI ,  I want to use mysqld_exporter to collect multiple mysql instances metrics on a host ,how to config the .my.cnf file? 
Now I run 3 mysql instances  use 3 port on one host ,I want to collect all the  instances metrics.

 thanks!

**Comment by SuperQ** [comment]
You will need to configure the mysqld_exporter to run on 3 different ports as well.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
