### ISSUE TITLE
Update to go-sql-driver/mysql 1.4.1

### ISSUE THREAD

**Issue by foosinn** [prometheus/mysqld_exporter#345]
Hey,

go-sql-driver/mysql just released 1.4.1. Is it possible to rebuild the official package against the latest version?

https://github.com/go-sql-driver/mysql/releases/tag/v1.4.1

## Version 1.4.1 (2018-11-14)

Bugfixes:

 - Fix TIME format for binary columns (#818)
 - Fix handling of empty auth plugin names (#835)
 - Fix caching_sha2_password with empty password (#826)
 - Fix canceled context broke mysqlConn (#862)
 - Fix OldAuthSwitchRequest support (#870)
 - Fix Auth Response packet for cleartext password (#887)

**Comment by SuperQ** [comment]
I'm traveling right now, but there's a few good reasons to cut a new release soon.
