### ISSUE TITLE
Use domain as dsn only hit one MySQL instance

### ISSUE THREAD

**Issue by huangsuoyuan** [prometheus/mysqld_exporter#349]
### Host operating system: output of `uname -a`

```
Ubuntu 16.04.4 LTS \n \l
```

### mysqld_exporter version: output of `mysqld_exporter --version`

```
mysqld_exporter, version 0.11.0 (branch: HEAD, revision: 5d7179615695a61ecc3b5bf90a2a7c76a9592cdd)
  build user:       root@3d3ff666b0e4
  build date:       20180629-15:00:35
  go version:       go1.10.3
```

### MySQL server version
MySQL 5.5

### mysqld_exporter command line flags

```
--no-collect.info_schema.tables
```

### What did you do that produced an error?
No error 

### What did you expect to see?
I am monitoring  a large number of mysql instances(10000+) with Mysqld exporters. These instances  divide into different clusters. A typical cluster is often made up with a master and three or more slaves. 

Our DBA use domain for load balance in slaves.

mysqld-exporter access these db servers with a domain, for example db-master-xxx.xx.com, db-slave-xxx.xx.com

The slave domain binds three ips with it. And as our business grows, our mysql instances are often scaled or migrated to other servers. So the slave instances' ips are always changing and I got very tired always changing exporter's config when scale or migration happens.

### What did you see instead?

So here I come and ask. When a domain is given as a dsn, can the exporter try to scrape all the instances behind that domain?

I think this demand is very common in large companies. If you guys are OK with this idea, I am very happy to make PR about it.

**Comment by SuperQ** [comment]
The mysqld_exporter is designed to communicate with MySQL over localhost, one-to-one with each instance of mysql. This is an intentional design to avoid the exporter being a SPoF.

The typical use case it to deploy an exporter automatically with each instance, and use Prometheus service discovery to find all available servers.

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by huangsuoyuan** [comment]
thank you very much !!
