### ISSUE TITLE
mysqld_exporter crashes and not restarting of its own

### ISSUE THREAD

**Issue by sattan66** [prometheus/mysqld_exporter#356]
we are using prometheus bosh release - 23.2.0 to monitor our cloud foundry and we are facing the below  issue with mysqld_exporter from our last upgrade to 23.2.0 . 

The mysqld_exporter crashes sometime and not restarting of its own and prometheus starts triggering the myqsld_exporter scrape error alerts. Manual restart of mysqld_exporter gives a temporary fix. 

### Host operating system: output of `uname -a`

Linux 86bc42a1-1cfa-47d5-bd5f-c2039175ec1a 4.4.0-81-generic #104~14.04.1-Ubuntu SMP Wed Jun 14 12:45:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### mysqld_exporter version: output of `mysqld_exporter --version`

mysqld_exporter, version 0.11.0 (branch: HEAD, revision: 5d7179615695a61ecc3b5bf90a2a7c76a9592cdd)
  build user:       root@3d3ff666b0e4
  build date:       20180629-15:00:35
  go version:       go1.10.3

### What did you do that produced an error?

NA

### What did you expect to see?

The exporter should restart automatically after the crash 

### What did you see instead?

once the exporter is crashed, it is unable to collect the metrics which in turn in reported by prometheus as mysqld_exporter scrape error. 

Below are few logs we found in mysql_exporter.stderr.log

```
time="2018-10-18T05:25:24Z" level=info msg="Listening on :9104" source="mysqld_exporter.go:232"
time="**2018-12-06T14:41:56Z**" level=error msg="Error pinging mysqld: dial tcp x.x.x.x:3306: connect: connection refused" source="exporter.go:119"
time="**2018-12-10T06:33:05Z**" level=info msg="Starting mysqld_exporter (version=0.11.0, branch=HEAD, revision=5d7179615695a61ecc3b5bf90a2a7c76a9592cdd)" source="mysqld_exporter.go:206"
time="2018-12-10T06:33:05Z" level=info msg="Build context (go=go1.10.3, user=root@3d3ff666b0e4, date=20180629-15:00:35)" source="mysqld_exporter.go:207"
time="2018-12-10T06:33:05Z" level=info msg="Enabled scrapers:" source="mysqld_exporter.go:218"
time="2018-12-10T06:33:05Z" level=info msg=" --collect.info_schema.tables" source="mysqld_exporter.go:222"
time="2018-12-10T06:33:05Z" level=info msg=" --collect.global_status" source="mysqld_exporter.go:222"
time="2018-12-10T06:33:05Z" level=info msg=" --collect.global_variables" source="mysqld_exporter.go:222"
time="2018-12-10T06:33:05Z" level=info msg=" --collect.slave_status" source="mysqld_exporter.go:222"
time="2018-12-10T06:33:05Z" level=info msg="Listening on :9104" source="mysqld_exporter.go:232"
```

**Comment by SuperQ** [comment]
Without a crash message, there's not much we can do here. This also sounds like a problem with bosh, not the exporter.

**Comment by ionphractal** [comment]
@SuperQ I don't quite understand why do you suspect bosh. Could you please explain?

Please correct me if I'm wrong, but as far as I understand the intended behavior of the exporter is:
- if the exporter looses connection to its service, it should retry to connect / scrape again (or if it was made to exit, below would happen), which would produce more log output
- if the exporter process exits (e.g. crash), monit should detect that and try to restart it
Both don't seem to happen.

Rather than crashing, it seems like the exporter process gets stuck?

**Comment by SuperQ** [comment]
> if the exporter looses connection to its service, it should retry to connect / scrape again (or if it was made to exit, below would happen), which would produce more log output

The exporter itself is stateless, it makes a new MySQL connection every time it's scraped. It then closes the connection. If the connection is lost mid-scrape, it will return an error. It will not exit on any MySQL problem.

> if the exporter process exits (e.g. crash), monit should detect that and try to restart it

This is not part of the exporter, monit is not included, this is part of your system/deployment. Exporters do not restart themselves, this is up to  your process supervisor.

I suspect there is something wrong with bosh, or your deployment.

**Comment by ionphractal** [comment]
@SuperQ Thanks for the clarification. Will setting log level to debug produce logs for each scrape run?

**Comment by SuperQ** [comment]
Yes, debug will include all results of each scrape in the log.

**Comment by sattan66** [comment]
Hi, 

We had the issue again, and here is the log attached along with strace output. 

cf_exporter-PROD/2fdbaee0-6986-4549-b2fb-cfc6fbe1529c:/var/vcap/sys/log/mysqld_exporter# ps -ef | grep mysqld
root     22183     1  0  2018 ?        00:08:31 mysqld_exporter --log.level=debug --web.listen-address=:9104
root     30733 30713  0 02:14 pts/0    00:00:00 grep --color=auto mysqld

**Error log**

time="2019-02-08T04:37:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T04:41:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T04:45:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T04:45:30Z" level=error msg="Error pinging mysqld: dial tcp 53.30.187.15:3306: connect: no route to host" source="exporter.go:119"
time="2019-02-08T04:49:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T04:53:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T04:57:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T05:01:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T05:05:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"
time="2019-02-08T05:09:27Z" level=debug msg="collect query: []" source="mysqld_exporter.go:142"


**Strace output from 15 mins**

cf_exporter-PROD/2fdbaee0-6986-4549-b2fb-cfc6fbe1529c:/var/vcap/sys/log/mysqld_exporter# strace -t -p 22183
Process 22183 attached
02:16:12 futex(0xc20f88, FUTEX_WAIT, 0, NULL) = 0
02:16:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:16:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:16:27 futex(0xc20690, FUTEX_WAKE, 1) = 1
02:16:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:16:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:16:27 futex(0xc20690, FUTEX_WAKE, 1) = 1
02:16:27 futex(0xc20f88, FUTEX_WAIT, 0, NULL) = 0
02:17:27 write(5, "\26\0\0\0\3SHOW GLOBAL VARIABLES", 26) = 26
02:17:27 read(5, 0xc4200ae000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:17:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:17:27 futex(0xc20690, FUTEX_WAKE, 1) = 1
02:17:27 read(5, "\1\0\0\1\2d\0\0\2\3def\22information_schema"..., 4096) = 4096
02:17:27 read(5, "l\0015\37\0\0\201\32innodb_api_disable_rowlo"..., 4067) = 4067
02:17:27 read(5, "\0\0\364\26innodb_old_blocks_time\0041000+"..., 4095) = 4095
02:17:27 read(5, "56\27\0\0t\21myisam_block_size\0041024\33\0\0"..., 4076) = 4076
02:17:27 read(5, "_audit_events\rCONNECT,QUERY\206\0\0\330\27"..., 4089) = 4089
02:17:27 read(5, "/vcap/store/mysql/; base_host = "..., 4055) = 2223
02:17:27 write(5, "\27\0\0\0\3SHOW ALL SLAVES STATUS", 27) = 27
02:17:27 read(5, 0xc4200ae000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:17:27 futex(0xc20f88, FUTEX_WAIT, 0, NULL^CProcess 22183 detached
<detached ...>


**Strace after the restart of the exporter:**

cf_exporter-PROD/2fdbaee0-6986-4549-b2fb-cfc6fbe1529c:/var/vcap/sys/log/mysqld_exporter# strace -t -p 30790
Process 30790 attached
02:29:19 epoll_pwait(4, {{EPOLLIN, {u32=248688384, u64=140540168548096}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 accept4(3, {sa_family=AF_INET, sin_port=htons(37868), sin_addr=inet_addr("53.30.184.56")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 5
02:29:27 epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=248688176, u64=140540168547888}}) = 0
02:29:27 getsockname(5, {sa_family=AF_INET, sin_port=htons(9104), sin_addr=inet_addr("53.30.187.126")}, [16]) = 0
02:29:27 setsockopt(5, SOL_TCP, TCP_NODELAY, [1], 4) = 0
02:29:27 setsockopt(5, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
02:29:27 setsockopt(5, SOL_TCP, TCP_KEEPINTVL, [180], 4) = 0
02:29:27 setsockopt(5, SOL_TCP, TCP_KEEPIDLE, [180], 4) = 0
02:29:27 accept4(3, 0xc420185778, [112], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 read(5, "GET /metrics HTTP/1.1\r\nHost: 53."..., 4096) = 200
02:29:27 write(2, "time=\"2019-02-11T02:29:27Z\" leve"..., 96) = 96
02:29:27 newfstatat(AT_FDCWD, "/proc", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
02:29:27 newfstatat(AT_FDCWD, "/proc/30790", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
02:29:27 openat(AT_FDCWD, "/proc/30790/stat", O_RDONLY|O_CLOEXEC) = 6
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=248687968, u64=140540168547680}}) = -1 EPERM (Operation not permitted)
02:29:27 epoll_ctl(4, EPOLL_CTL_DEL, 6, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
02:29:27 read(6, "30790 (mysqld_exporter) R 1 3078"..., 512) = 314
02:29:27 read(6, "", 1222)              = 0
02:29:27 close(6)                       = 0
02:29:27 openat(AT_FDCWD, "/proc/stat", O_RDONLY|O_CLOEXEC) = 6
02:29:27 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=248687968, u64=140540168547680}}) = 0
02:29:27 fcntl(6, F_GETFL)              = 0x8000 (flags O_RDONLY|O_LARGEFILE)
02:29:27 fcntl(6, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
02:29:27 read(6, "cpu  299982559 2 55017564 401719"..., 4096) = 849
02:29:27 read(6, "", 3247)              = 0
02:29:27 epoll_ctl(4, EPOLL_CTL_DEL, 6, {0, {u32=0, u64=0}}) = 0
02:29:27 close(6)                       = 0
02:29:27 openat(AT_FDCWD, "/proc/30790/fd", O_RDONLY|O_CLOEXEC) = 6
02:29:27 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=248687968, u64=140540168547680}}) = -1 EPERM (Operation not permitted)
02:29:27 epoll_ctl(4, EPOLL_CTL_DEL, 6, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
02:29:27 getdents64(6, /* 9 entries */, 4096) = 216
02:29:27 getdents64(6, /* 0 entries */, 4096) = 0
02:29:27 close(6)                       = 0
02:29:27 openat(AT_FDCWD, "/proc/30790/limits", O_RDONLY|O_CLOEXEC) = 6
02:29:27 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=248687968, u64=140540168547680}}) = -1 EPERM (Operation not permitted)
02:29:27 epoll_ctl(4, EPOLL_CTL_DEL, 6, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
02:29:27 read(6, "Limit                     Soft L"..., 4096) = 1323
02:29:27 read(6, "", 2773)              = 0
02:29:27 close(6)                       = 0
02:29:27 socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 6
02:29:27 setsockopt(6, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
02:29:27 connect(6, {sa_family=AF_INET, sin_port=htons(3306), sin_addr=inet_addr("53.30.187.15")}, 16) = -1 EINPROGRESS (Operation now in progress)
02:29:27 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=248687968, u64=140540168547680}}) = 0
02:29:27 futex(0xc20f88, FUTEX_WAIT, 0, NULL) = 0
02:29:27 write(6, "\26\0\0\0\3SHOW GLOBAL VARIABLES", 26) = 26
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\2d\0\0\2\3def\22information_schema"..., 4096) = 4096
02:29:27 mmap(0xc420200000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420200000
02:29:27 mmap(0xc41ffe8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffe8000
02:29:27 read(6, "l\0015\37\0\0\201\32innodb_api_disable_rowlo"..., 4067) = 4067
02:29:27 read(6, "\0\0\364\26innodb_old_blocks_time\0041000+"..., 4095) = 4095
02:29:27 read(6, "56\27\0\0t\21myisam_block_size\0041024\33\0\0"..., 4076) = 4076
02:29:27 read(6, "_audit_events\rCONNECT,QUERY\206\0\0\330\27"..., 4089) = 4089
02:29:27 read(6, "/vcap/store/mysql/; base_host = "..., 4055) = 2223
02:29:27 write(6, "\27\0\0\0\3SHOW ALL SLAVES STATUS", 27) = 27
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {{EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, 0, NULL) = 1
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\0017%\0\0\2\3def\0\0\0\17Connection_name"..., 4096) = 2372
02:29:27 write(6, "\227\0\0\0\3\n\t\tSELECT\n\t\t    SCHEMA_NAME"..., 155) = 155
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\1N\0\0\2\3def\22information_schema"..., 4096) = 319
02:29:27 write(6, "\23\0\0\0\3SHOW GLOBAL STATUS", 23) = 23
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\2^\0\0\2\3def\22information_schema"..., 4096) = 4096
02:29:27 read(6, "\0\240\25Com_show_slave_status\00524309\31\0"..., 4094) = 4094
02:29:27 read(6, "rged_inserts\003309\27\0\0$\22Innodb_ibuf"..., 4081) = 4081
02:29:27 read(6, "id_wait_time\0010\34\0\0\221\31Master_gtid_w"..., 4086) = 4086
02:29:27 read(6, "1628\23\0\0\26\17wsrep_connected\2ON\25\0\0\27\22"..., 4071) = 1585
02:29:27 mmap(0xc420300000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420300000
02:29:27 mmap(0xc41ffe0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffe0000
02:29:27 write(6, "\371\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 509) = 509
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {{EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, 0, NULL) = 1
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 838
02:29:27 write(6, "\3\2\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 519) = 519
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 3207
02:29:27 write(6, "\373\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 511) = 511
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 1565
02:29:27 write(6, "\366\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 506) = 506
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 4096
02:29:27 read(6, "ct\00238\00516384\00516384\0010\0G\0\0>\4ccdb\21sp"..., 4048) = 450
02:29:27 write(6, "\371\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 509) = 509
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, 0, NULL) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 542
02:29:27 write(6, "\371\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 509) = 509
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 542
02:29:27 write(6, "\367\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 507) = 507
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 912
02:29:27 write(6, "\370\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 508) = 508
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 602
02:29:27 write(6, "\374\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 512) = 512
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 542
02:29:27 write(6, "\371\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 509) = 509
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 607
02:29:27 write(6, "\5\2\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 521) = 521
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:27 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:27 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 953
02:29:27 write(6, "\373\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 511) = 511
02:29:27 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:27 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:27 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:28 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:28 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 689
02:29:28 write(6, "\377\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 515) = 515
02:29:28 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:28 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:28 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:28 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:28 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 1683
02:29:28 write(6, "\371\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 509) = 509
02:29:28 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:28 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:28 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:28 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:28 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 817
02:29:28 write(6, "\366\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 506) = 506
02:29:28 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:28 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:28 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:28 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:28 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 673
02:29:28 write(6, "\365\1\0\0\3\n\t\tSELECT\n\t\t    TABLE_SCHEM"..., 505) = 505
02:29:28 read(6, 0xc4201d3000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:28 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:28 epoll_pwait(4, {{EPOLLIN|EPOLLOUT, {u32=248687968, u64=140540168547680}}}, 128, -1, NULL) = 1
02:29:28 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:28 read(6, "\1\0\0\1\vL\0\0\2\3def\22information_schema"..., 4096) = 1630
02:29:28 write(6, "\1\0\0\0\1", 5)      = 5
02:29:28 epoll_ctl(4, EPOLL_CTL_DEL, 6, {0, {u32=0, u64=0}}) = 0
02:29:28 close(6)                       = 0
02:29:28 mmap(0xc420400000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420400000
02:29:28 mmap(0xc41ffd8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffd8000
02:29:28 mmap(0xc000001000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000001000
02:29:28 mmap(NULL, 1439992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd20ebc6000
02:29:28 futex(0xc42003e948, FUTEX_WAKE, 1) = 1
02:29:28 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:28 futex(0xc20770, FUTEX_WAKE, 1) = 1
02:29:28 futex(0xc20690, FUTEX_WAKE, 1) = 1
02:29:28 mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd20ebb6000
02:29:28 mmap(0xc420500000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420500000
02:29:28 mmap(0xc41ffd0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffd0000
02:29:28 write(5, "HTTP/1.1 200 OK\r\nContent-Encodin"..., 4096) = 4096
02:29:28 write(5, "\336\355\6)qzF\271\351\366\254\354f\37\30\n\367;\35J\275\35HA\376\16\2457=\276`T"..., 19232) = 19232
02:29:28 epoll_pwait(4, {}, 128, 0, NULL) = 0
02:29:28 read(5, 0xc4201ab000, 4096)    = -1 EAGAIN (Resource temporarily unavailable)
02:29:28 futex(0xc20f88, FUTEX_WAIT, 0, NULL

Still it is behaving same, the exporter is not restarting after it crashes.

**Comment by sattan66** [comment]
Hi, 

Can you please review the above strace and help me if any changes to be done in my configuration .

Thanks.

**Comment by SuperQ** [comment]
Sorry, but this seems like a system problem, and not related to the exporter.

**Comment by wamayall** [comment]
I have the same issue, for your test environment try 4,000 databases, 5 tables with the exact schema, accounting for 18TB for mysql datadir, then query the information_schema that will return millions of rows, is there a timeout in the code to kill that query?  If so, what is the command issued?  Doing a "kill PID;" will orphan that query on the server, if you killed it successfully, then why try it again?  I suspect there is a timeout set if a return doesn't happen and that query IS successfully killed, But it started a FULL TABLE Scan, this repeats over and over 24/7, when my application is idle, disk utilization is 40% as my application starts to receive requests, the disk utilization jumps to between 90% and 100% busy, and with 32 CPUs, only 10 are in use and the load is what you would expect ~10, but the slaves fall behind as context switching is running 200K, the disks are max'ed, my poor 10 CPUs out of 32 never get a break.  So, I do feel your point is valid, that someone at my company created a metric that can take down a server with 32 CPUs, 500GB of RAM, 50TB of disk.  So yes, part of the problem is the person that wrote the Metric and it would be nice to let the End User of Your Product know they are creating a query that can KILL their PRODUCTION database!
