### ISSUE TITLE
Can mysqld_expoter read config file?

### ISSUE THREAD

**Issue by pc10201** [prometheus/mysqld_exporter#357]
I use cloud database service(like aws rds).

I want to use open multi mysqld_expoter  programs on one cloud host to monitor multi rds.

But mysqld_expoter read environment variable DATA_SOURCE_NAME.

So I must use docker to run multi mysqld_expoter  program.

Can mysqld_expoter  read config file to get DATA_SOURCE_NAME?

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
