### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "argument list too long"

### ISSUE THREAD

**Issue by welyss** [prometheus/mysqld_exporter#359]
Hi!
We run a mysqld_exporter on kubernetes, and it works well, but after a few days, it crashed, and all of logs is only:
**standard_init_linux.go:178: exec user process caused "argument list too long"**

I found that the reason this occurs is because bash actually expands the asterisk to every matching file, producing a very long command line.
but i don't know what mysqld_exporter actually do cause this error.
i want to know the reason, then i know what i should do for it. Thanks!!!

### Host operating system: output of `uname -a`
Linux mysqlexp-dev-dm-54bcbbf7df-l5j57 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 GNU/Linux

### mysqld_exporter version: output of `mysqld_exporter --version`
mysqld_exporter, version 0.11.0 (branch: HEAD, revision: 5d7179615695a61ecc3b5bf90a2a7c76a9592cdd)
  build user:       root@3d3ff666b0e4
  build date:       20180629-15:00:35
  go version:       go1.10.3

### MySQL server version
mysql> select version();
+-----------+
| version() |
+-----------+
| 5.6.32    |
+-----------+
1 row in set (0.00 sec)

### mysqld_exporter command line flags
command: ['/bin/mysqld_exporter', '--web.listen-address=:8080', '--web.telemetry-path=/hbec/metrics']

### What did you do that produced an error?
rescale on kubernetes, set scale to 0 and when it is 0/0 i scale it to 1 again, and it works.

### What did you expect to see?
i don't know the real reason about this error.

### What did you see instead?
na

**Comment by brian-brazil** [comment]
I'd guess this is due to you having too much in your environment variables.

**Comment by SuperQ** [comment]
This looks like a Docker problem, not an error from the exporter.

**Comment by welyss** [comment]
yesterday i try it with "--log.level=debug" args, after crashed, i got some other error message, but i don't sure it's the same reason than before, new message is:
failed to open log file "/var/log/pods/12713242-1247-11e9-8156-029cc9f85bc5/mysqld-exporter_72.log": open /var/log/pods/12713242-1247-11e9-8156-029cc9f85bc5/mysqld-exporter_72.log: no such file or directory
and in pod, there is no pods directory:
/ # ls -lh /var/log/
ls: /var/log/: No such file or directory
/ # ls /var
run    spool  www
/ # 
================================
i'm not sure where need to open the log file "/var/log/pods/12713242-1247-11e9-8156-029cc9f85bc5/mysqld-exporter_72.log".
maybe it is docker problem, i will change it to another new version kubenetes, and try it.

**Comment by welyss** [comment]
thanks reply!
it should docker problem. closed the issue
