### ISSUE TITLE
Ping mysqld: dial tcp 127.0.0.1:3306: connect: connection refused

### ISSUE THREAD

**Issue by ColorfulWolf** [prometheus/mysqld_exporter#360]
MySQL server version: 8

I enter the mysqld-exporter docker container and see its logs:

`msg="Error pinging mysqld: dial tcp 127.0.0.1:3306: connect: connection refused" source="exporter.go:119"`

and my exporter account authority is:
```
Grants for exporter@localhost                                              |
+----------------------------------------------------------------------------+
| GRANT SELECT, PROCESS, REPLICATION CLIENT ON *.* TO `exporter`@`localhost`
```
So, is that my mysql configuration wrong? How to deal with it :)

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
