### ISSUE TITLE
unknown long flag '--collect.info_schema.schemastats'

### ISSUE THREAD

**Issue by estahn** [prometheus/mysqld_exporter#365]
### Host operating system: output of `uname -a`
```
docker run -it -exec prom/mysqld-exporter
```

### mysqld_exporter version: output of `mysqld_exporter --version`
```
mysqld_exporter, version 0.11.0 (branch: HEAD, revision: 5d7179615695a61ecc3b5bf90a2a7c76a9592cdd)
  build user:       root@3d3ff666b0e4
  build date:       20180629-15:00:35
  go version:       go1.10.3
```

### MySQL server version
N/A

### mysqld_exporter command line flags
```--collect.info_schema.schemastats``` and ```--no-collect.info_schema.schemastats```

### What did you do that produced an error?

```
docker run -it -exec prom/mysqld-exporter --collect.info_schema.schemastats
mysqld_exporter: error: unknown long flag '--collect.info_schema.schemastats', try --help
```

### What did you expect to see?

It working according to the README.

### What did you see instead?

Not working.

**Comment by SuperQ** [comment]
This is an unreleased feature. It will be included in the next release.

**Comment by estahn** [comment]
@SuperQ Do you guys plan on cutting a release soon?
