### ISSUE TITLE
Release version v0.12.0

### ISSUE THREAD

**Issue by thomasbarton** [prometheus/mysqld_exporter#374]
Could we release a new docker image and version please . ( v0.12.0 ).  It has been 9 months since `v0.11.0` was released.

Thank You

**Comment by zstyblik** [comment]
@SuperQ please? :crying_cat_face:

**Comment by thomasbarton** [comment]
@SuperQ There isnt a docker tag for this version.  Could a new tag be pushed to docker hub.  I am not a fan of using `latest`.

Source -> https://hub.docker.com/r/prom/mysqld-exporter/tags
