### ISSUE TITLE
Error pinging mysqld: dial tcp 127.0.0.1:3306

### ISSUE THREAD

**Issue by sandipdivekar1** [prometheus/mysqld_exporter#394]
I have configured mysqldexporter user using this command. 
`CREATE USER "mysqldexporter"@"localhost" IDENTIFIED BY "**";`

I have configured exporter cnf file like below. my.cnf
```
[client]
host=localhost
user=mysqldexporter
password=***

```

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
