### ISSUE TITLE
Which parameter should be set in the config file to get the TPS of mysql server ?

### ISSUE THREAD

**Issue by Myshiner** [prometheus/mysqld_exporter#402]
Hi, i get the QPS which named "Current QPS" in the mysql overview page, and the corresponding parameter is mysql_global_status_queries, so which parameter should be set to get mysql TPS index ?

Thx.

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
