### ISSUE TITLE
Push version `v0.12.0` to docker hub

### ISSUE THREAD

**Issue by thomasbarton** [prometheus/mysqld_exporter#408]
Thank you for releasing version `v0.12.0` !

Could you please push a docker tag for this version too :)

Docker Hub link showing tags -> https://hub.docker.com/r/prom/mysqld-exporter/tags
Previous ticket -> https://github.com/prometheus/mysqld_exporter/issues/374

This issue is done when Docker hub has a tagged version for `v0.12.0`

Thank You!

**Comment by eddycharly** [comment]
Any news on this ?

**Comment by SuperQ** [comment]
Strange, normally that happens automatically with our pipeline.. @simonpasquier might be able to help with this.

**Comment by simonpasquier** [comment]
Yes there's been a hiccup with the [release](https://github.com/prometheus/mysqld_exporter/pull/407) job which had been fixed by #407.

I think the simplest fix would be to release `v0.12.1` as the difference between master and v0.12.0 is only #407.

**Comment by thomasbarton** [comment]
Releasing version `v0.12.1` would be good for me too.  Let me know when that happens and ill gladly close this ticket

**Comment by pantaoran** [comment]
Yes please do this, I also need the latest version please.

**Comment by SuperQ** [comment]
Okie! 0.12.1 has been pushed up to Docker.
