### ISSUE TITLE
Use mysqld_exporter for several mysql instance

### ISSUE THREAD

**Issue by iglov** [prometheus/mysqld_exporter#415]
Hey there! 
It is possible to use docker image with mysqld_exporter for several mysql nodes? For example i have 1 mysqld_exporter on some docker-server and mysql-1, mysql-2, mysql-3, mysql-n nodes, how i can grab metrics from them all? Or i have to install mysqld_exporter on my each mysql node?

**Comment by SuperQ** [comment]
Generally you deploy the mysqld_exporter on each mysql-X node as part of your standard deployment. This allows the exporter to talk to mysql over localhost, avoiding network issues.

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by iglov** [comment]
Thank you so much! ^_^
