### ISSUE TITLE
collect.info_schema.tables.databases does not collect any metrics in :latest

### ISSUE THREAD

**Issue by jonathanhartley** [prometheus/mysqld_exporter#416]
ReadMe out of date it says Enabled By Default (it is not)

Pulling :latest 
the flag:
--collect.info_schema.tables.databases=* or (any single name of schema) 
does not output any metrics
container running the following flags:
            "image": "prom/mysqld-exporter",
            "args": [
              "--collect.global_variables",
              "--collect.engine_innodb_status",
              "--collect.info_schema.innodb_cmp",
              "--collect.info_schema.innodb_metrics",
              "--collect.info_schema.innodb_cmpmem",
              "--collect.info_schema.tables.databases=book",
              "--collect.info_schema.innodb_tablespaces",
              "--collect.info_schema.processlist",
              "--collect.slave_hosts"
            ],
logs output:
time="2019-07-30T05:36:50Z" level=info msg="Enabled scrapers:" source="mysqld_exporter.go:269"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.info_schema.innodb_tablespaces" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.info_schema.innodb_metrics" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.global_status" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.global_variables" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.slave_status" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.info_schema.processlist" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.slave_hosts" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.info_schema.innodb_cmp" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.info_schema.innodb_cmpmem" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.info_schema.query_response_time" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg=" --collect.engine_innodb_status" source="mysqld_exporter.go:273"
time="2019-07-30T05:36:50Z" level=info msg="Listening on :9104" source="mysqld_exporter.go:283"

In the above example the schema `book` exists and SHOW TABLE STATUS gives:
mysql> show table status\G
*************************** 1. row ***************************
           Name: bet
         Engine: InnoDB
        Version: 10
     Row_format: Compressed
           Rows: 1843552
 Avg_row_length: 159
    Data_length: 294043648
Max_data_length: 0
   Index_length: 398573568
      Data_free: 35127296
 Auto_increment: NULL
    Create_time: 2019-07-30 05:36:44
    Update_time: 2019-07-30 12:59:35
     Check_time: NULL
      Collation: utf8mb4_unicode_ci
       Checksum: NULL
 Create_options: row_format=COMPRESSED partitioned
        Comment:
*************************** 2. row ***************************
           Name: bet_outcome
         Engine: InnoDB
        Version: 10
     Row_format: Compressed
           Rows: 3318701
 Avg_row_length: 81
    Data_length: 270008320
Max_data_length: 0
   Index_length: 507518976
      Data_free: 40370176
 Auto_increment: NULL
    Create_time: 2019-07-30 05:36:44
    Update_time: 2019-07-30 12:59:35
     Check_time: NULL
      Collation: utf8mb4_unicode_ci
       Checksum: NULL
 Create_options: row_format=COMPRESSED partitioned
        Comment:
*************************** 3. row ***************************
           Name: outcomes
         Engine: InnoDB
        Version: 10
     Row_format: Compressed
           Rows: 425784
 Avg_row_length: 48
    Data_length: 20815872
Max_data_length: 0
   Index_length: 12115968
      Data_free: 2621440
 Auto_increment: NULL
    Create_time: 2019-07-30 05:36:44
    Update_time: 2019-07-30 12:59:31
     Check_time: NULL
      Collation: ascii_general_ci
       Checksum: NULL
 Create_options: row_format=COMPRESSED
        Comment:
*************************** 4. row ***************************
           Name: strike_event
         Engine: InnoDB
        Version: 10
     Row_format: Dynamic
           Rows: 0
 Avg_row_length: 0
    Data_length: 16384
Max_data_length: 0
   Index_length: 0
      Data_free: 0
 Auto_increment: NULL
    Create_time: 2019-07-30 05:36:44
    Update_time: NULL
     Check_time: NULL
      Collation: utf8mb4_unicode_ci
       Checksum: NULL
 Create_options:
        Comment:
4 rows in set (0.00 sec)

**Comment by jonathanhartley** [comment]
ReadMe out of date it says Enabled By Default (it is not)

**Comment by SuperQ** [comment]
Fixed readme with https://github.com/prometheus/mysqld_exporter/commit/66dec6abde47ba14e33a69ea9fed4a7c114bc7ad.
