### ISSUE TITLE
Change the value of max_binlog_cache_size

### ISSUE THREAD

**Issue by hh-project-config** [prometheus/mysqld_exporter#418]
Thanks for providing this useful container. 

I am doing a research aiming at finding issues in configuration files. I have a question about one MySQL config: `max_binlog_cache_size`. It seems the [official document](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_cache_size) says "The maximum recommended value is 4GB; this is due to the fact that MySQL currently cannot work with binary log positions greater than 4GB."

However, the default value is 18446744073709551615, which is much larger than the recommended value. 

Shall we change the value to 4GB? 
Thanks!

**Comment by SuperQ** [comment]
This doesn't seem to have anything to do with the mysqld_exporter.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
