### ISSUE TITLE
Can mysqld_exporter be deployed on different host rather than MySQL host

### ISSUE THREAD

**Issue by xinghua0123** [prometheus/mysqld_exporter#438]
I am exploring the prometheus, since it's using 'pull' mechanism instead of 'push'. So want to check if it works that I deploy the mysqld_exporter on host 1, and it can expose the mysql metrics on host 2(where mysql server is running).

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
