### ISSUE TITLE
Disabled binary log stops data collection already

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#44]
I noticed on the server with binary log disabled I get error message:

INFO[0014] Error scraping binlog size: Error 1381: You are not using binary logging  file=mysqld_exporter.go line=549
INFO[0265] Error scraping binlog size: Error 1381: You are not using binary logging  file=mysqld_exporter.go line=549

This causes all further metric collection to stop.  Better behavior would be to collect all metrics which are available in the given instance and ignore those which can't be collected.

Current behavior means  test servers which often do not have binary log enabled need to run different exporter configuration than other ones.

**Comment by roman-vynar** [comment]
I believe there is the same with other options as well.

If you enable all possible metrics and something is missed on MySQL, the exporter will not expose the rest even successful metrics.

INFO[0000] Error scraping performance schema: Error 1146: Table 'performance_schema.table_io_waits_summary_by_table' doesn't exist  file=mysqld_exporter.go line=555

**Comment by SuperQ** [comment]
Yes, this came up in a previous PR, it's been on my TODO list to add some feature auto-detection to avoid this kind of problem.

**Comment by PeterZaitsev** [comment]
Two reasons

1) Consistency 

2) Capturing data with different frequency.    I would like to capture status (and status only) with 1 second resolution as high resolution data is needed for it.  I do not need 1 second resolution for variables as they change very slowly.      I when would like to capture everything else with 30 sec or one minute resolution which currently means I have to get duplicate record for status as well and try to deal with that. It would be much cleaner to avoid creating duplicate on the first place

**Comment by roman-vynar** [comment]
Peter,

seems you replied to the wrong issue.

> On Oct 6, 2015, at 18:00, PeterZaitsev <notifications@github.com> wrote:
> 
> Two reasons
> 
> 1) Consistency
> 
> 2) Capturing data with different frequency. I would like to capture status (and status only) with 1 second resolution as high resolution data is needed for it. I do not need 1 second resolution for variables as they change very slowly. I when would like to capture everything else with 30 sec or one minute resolution which currently means I have to get duplicate record for status as well and try to deal with that. It would be much cleaner to avoid creating duplicate on the first place
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/prometheus/mysqld_exporter/issues/44#issuecomment-145886052>.
> 

—
Roman Vynar
Lead Platform Engineer, Percona
Phone: 1-919-794-5403 (UTC +3)

**Comment by SuperQ** [comment]
This should be fixed, we now have enable/disable flags on all collection methods.
