### ISSUE TITLE
create mysql user error

### ISSUE THREAD

**Issue by luoMonkeyKing** [prometheus/mysqld_exporter#445]
Hi, I get an error when executing the provided create mysql user statement. My mysql version is: (Server version: 5.6.35 MySQL Community Server)
The execution statement is: CREATE USER 'mysqld_exporter' @ '%' IDENTIFIED BY '123456' WITH 'MAX_USER_CONNECTIONS' 3;
The error message is: "ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MAX_USER_CONNECTIONS 3' at line 1"
Can you help me see it, thank you

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
