### ISSUE TITLE
Make all data sources configurable

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#45]
mysqld exporter can report on multiple data sources, most of them can be enabled through collect.info_schema.userstats and similar settings however things like global status and global variables are always scrapped and reported:

if err = scrapeGlobalStatus(db, ch); err != nil {
		log.Println("Error scraping global state:", err)
		return
	}

It would be good to have options for them too so they can be disabled if needed (keeping them on by default)

**Comment by SuperQ** [comment]
I don't see any use case for disabling global status and global variables, can you give any examples of where we wouldn't want them?

**Comment by PeterZaitsev** [comment]
Two reasons

1) Consistency

2) Capturing data with different frequency. I would like to capture status (and status only) with 1 second resolution as high resolution data is needed for it. I do not need 1 second resolution for variables as they change very slowly. I when would like to capture everything else with 30 sec or one minute resolution which currently means I have to get duplicate record for status as well and try to deal with that. It would be much cleaner to avoid creating duplicate on the first place

**Comment by SuperQ** [comment]
Capturing everything with high frequency isn't a problem for Prometheus.
Until you get into the use case of 1000s of servers, you really want to
enable as much of

Besides, SHOW GLOBAL STATUS is a terrible place to get metrics from,
scraping it at high frequency is nearly useless.  It only has minimal
detail, with very little about actual schema metrics.

**Comment by SuperQ** [comment]
So let me possibly explain more.  The design goal for Prometheus is to provide somewhat near real-time metrics.  More importantly, alerting based on those metrics.  A typical rate expression operates on a 1-5 minute timefreame, not seconds.  Typical prometheus scraping is on the order of 15-30 seconds, this provides more than enough detail for a 5min rate function.  If you want 1min rate functions, 10-15s scraping provides more than enough data points.

**Comment by PeterZaitsev** [comment]
It is not problem for Prometheus but is is a problem for MySQL causing way too much overhead in many cases, for example if you're looking at instance with large number of tables. 

High frequency SHOW GLOBAL STATUS  has different purpose -  It allows to see the micro incidents and stalls before they become major issue.     For example  I look at Threads_Running  - if there is some global stall in the system it will spike and stay high for couple of seconds only before going down.  
From this when I can look at why it could be the issue which for example can be spike in the amount of IO requests sent to the disk which can be caused by how purge or checkpointing scheduling works.

We're doing a lot of advanced problem troubleshooting as well as development so we often need to zoom to understand it.

**Comment by SuperQ** [comment]
Ahh, yes, this is a very typical misunderstanding of how to use Prometheus.  Threads_Running is a fast-moving gauge, these kinds of metrics are not how you want to debug things.  I know it's how you do things now, but it's "the wrong way" to do it, especially with Prometheus.

There are much better ways to find these events, but high-speed scraping of gauges is not what Prometheus is for.  I'd love to go into more detail, maybe we can chat over IRC or some other real-time method.

**Comment by PeterZaitsev** [comment]
Brian,

I agree there are many use cases when very high level of resolution is not needed.  I just state what there are cases when you need smaller amount of metrics but with high resolution.  

1 second is already a long time - when you're looking at target response time for any interactive database usage it is going to be milliseconds if not fractions of them for most queries.  Sampling longer than that such as 5 sec will mean what you can miss a lot of incidents behind the average

**Comment by PeterZaitsev** [comment]
Ben,

Drop me a note at pz@percona.com and we can find way to connect

**Comment by brian-brazil** [comment]
I'm not Ben :)

For the type of debugging you're doing a handful of stats per server monitored every 1s can be very useful and we should ultimately support our users doing this (though it'll be tricky with some exporters).

For anything that doesn't cover, you're going to have to rely on logs and the like.

**Comment by PeterZaitsev** [comment]
Sorry Brian, Ben I indeed confused your names. 

My point is at Percona we have our methods we use to troubleshoot Performance problems. We have variety of our tools and scripts to capture data with 1 second resolution and we looked at Prometheus as potentially better and more modern platform doing it.

**Comment by SuperQ** [comment]
Ok, PR is up: https://github.com/prometheus/mysqld_exporter/pull/46

**Comment by SuperQ** [comment]
PR Merged.
