### ISSUE TITLE
'exporter' has exceeded the 'max_user_connections'

### ISSUE THREAD

**Issue by sandeepnethi** [prometheus/mysqld_exporter#461]
### Host operating system: output of `uname -a`
Centos

### mysqld_exporter version: output of `mysqld_exporter --version`

0.11.0

### MySQL server version
5.7.25

### mysqld_exporter command line flags

MYSQLD_EXPORTER_OPTS=" --log.level=info --exporter.lock_wait_timeout=2 --web.listen-address=:9104 --web.telemetry-path=/metrics --collect.auto_increment.columns --collect.binlog_size --collect.global_status --collect.global_variables --collect.info_schema.innodb_metrics --collect.info_schema.innodb_cmp --collect.info_schema.innodb_cmpmem --collect.info_schema.processlist --collect.info_schema.query_response_time --collect.info_schema.tables --collect.info_schema.tablestats --collect.info_schema.userstats --collect.perf_schema.eventswaits --collect.perf_schema.file_events --collect.perf_schema.indexiowaits --collect.perf_schema.tableiowaits --collect.perf_schema.tablelocks --collect.slave_status "
DATA_SOURCE_NAME='exporter:xxxxxxxxxxxxxxxxxxxxxxx@(127.0.0.1:3306)/'

Error:

level=error msg="Error pinging mysqld: Error 1226: User 'exporter' has exceeded the 'max_user_connections' resource (current value: 10)" source="exporter.go:119"

level=error msg="Error scraping for collect.perf_schema.file_events: Error 1226: User 'exporter' has exceeded the 'max_user_connections' resource (current value: 10)" source="exporter.go:138"

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
