### ISSUE TITLE
Access denied for user 'exporter'@'::1'

### ISSUE THREAD

**Issue by hjfeng1988** [prometheus/mysqld_exporter#468]
### Host operating system: output of `uname -a`
[root@XM-v122 ~]# uname -a
Linux XM-v122 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### mysqld_exporter version: output of `mysqld_exporter --version`

[root@XM-v122 ~]# /usr/local/mysqld_exporter/mysqld_exporter --version
mysqld_exporter, version 0.12.1 (branch: HEAD, revision: 48667bf7c3b438b5e93b259f3d17b70a7c9aff96)
  build user:       root@0b3e56a7bc0a
  build date:       20190729-12:35:58
  go version:       go1.12.7
### MySQL server version
[root@XM-v122 ~]# mysql --version
mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper
### mysqld_exporter command line flags

/usr/local/mysqld_exporter/mysqld_exporter --config.my-cnf=/usr/local/mysqld_exporter/.my.cnf
### What did you do that produced an error?
Grant user follow this project
`GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'localhost';`
When mysqld_exporter start and connect mysqld,I get error like below:
```
May 11 16:38:30 XM-v122 systemd: Started mysqld_exporter.
May 11 16:38:30 XM-v122 systemd: Starting mysqld_exporter...
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg="Starting mysqld_exporter (version=0.12.1, branch=HEAD, revision=48667bf7c3b438b5e93b259f3d17b70a7c9aff96)" source="mysqld_exporter.go:257"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg="Build context (go=go1.12.7, user=root@0b3e56a7bc0a, date=20190729-12:35:58)" source="mysqld_exporter.go:258"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg="Enabled scrapers:" source="mysqld_exporter.go:269"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg=" --collect.global_status" source="mysqld_exporter.go:273"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg=" --collect.global_variables" source="mysqld_exporter.go:273"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg=" --collect.slave_status" source="mysqld_exporter.go:273"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg=" --collect.info_schema.innodb_cmp" source="mysqld_exporter.go:273"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg=" --collect.info_schema.innodb_cmpmem" source="mysqld_exporter.go:273"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg=" --collect.info_schema.query_response_time" source="mysqld_exporter.go:273"
May 11 16:38:30 XM-v122 mysqld_exporter: time="2020-05-11T16:38:30+08:00" level=info msg="Listening on :9104" source="mysqld_exporter.go:283"
May 11 16:38:42 XM-v122 mysqld_exporter: time="2020-05-11T16:38:42+08:00" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'exporter'@'::1' (using password: YES)" source="exporter.go:146"
May 11 16:38:42 XM-v122 mysqld_exporter: time="2020-05-11T16:38:42+08:00" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'exporter'@'::1' (using password: YES)" source="exporter.go:146"
May 11 16:38:48 XM-v122 mysqld_exporter: time="2020-05-11T16:38:48+08:00" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'exporter'@'::1' (using password: YES)" source="exporter.go:146"
```
I change grants from 'exporter'@'localhost' to 'exporter'@'%',The problem is solved.
### What did you expect to see?
I don't want make bigger grants.

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
