### ISSUE TITLE
does mysql_exporter need a connection?

### ISSUE THREAD

**Issue by gjiuyi** [prometheus/mysqld_exporter#476]
i restart mysql,and did't use it.then i use mysql_exporter,
when it works fine,i query mysql_global_status_threads_connected the result is 1, then i run another mysql_exporter .now i have 2 mysql_exporter run in my system.and both of them works fine.
at that time,i query mysql_global_status_threads_connected again ,th result is still 1.why it not be 2.

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
