### ISSUE TITLE
Connection error ? A lot of Error scraping

### ISSUE THREAD

**Issue by Jean-MarcS** [prometheus/mysqld_exporter#477]
### Host operating system: output of `uname -a`
Linux mysql 4.15.18-13-pve #1 SMP PVE 4.15.18-37 (Sat, 13 Apr 2019 21:09:15 +0200) x86_64 GNU/Linux

### mysqld_exporter version: output of `mysqld_exporter --version`
Last one from July 2019

### MySQL server version
10.4.13-MariaDB-1:10.4.13+maria~buster-log

### mysqld_exporter command line flags
ExecStart=/usr/local/bin/mysqld_exporter \
--config.my-cnf /etc/.mysqld_exporter.cnf \
--collect.auto_increment.columns \
--collect.binlog_size \
--collect.global_status \
--collect.global_variables \
--collect.info_schema.innodb_metrics \
--collect.info_schema.processlist \
--collect.info_schema.tablestats \
--collect.info_schema.query_response_time \
--collect.info_schema.tables \
--collect.info_schema.userstats \
--collect.perf_schema.eventswaits \
--collect.perf_schema.file_events \
--collect.perf_schema.indexiowaits \
--collect.perf_schema.tableiowaits \
--collect.perf_schema.tablelocks \
--exporter.lock_wait_timeout 10 \
--web.listen-address=0.0.0.0:9104

### What did you do that produced an error?
Just installed and run it

### What did you expect to see?
Not that much errors, and unfragmented graphs

### What did you see instead?

Lots of error in my logs

For example :

`Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.perf_schema.file_events: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.info_schema.innodb_cmpmem: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.perf_schema.tablelocks: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.binlog_size: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.info_schema.query_response_time: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.perf_schema.indexiowaits: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.info_schema.tables: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.slave_status: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.info_schema.innodb_cmp: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.perf_schema.tableiowaits: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:41+02:00" level=error msg="Error scraping for collect.perf_schema.eventswaits: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:41 mysql mysqld[17375]: 2020-06-15 12:33:41 106002 [Warning] Aborted connection 106002 to db: 'unconnected' user: 'mysqld_exporter' host: '192.168.1.200' (Got an error writing communication packets)
Jun 15 12:33:56 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:56+02:00" level=error msg="Error scraping for collect.info_schema.userstats: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:56 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:56+02:00" level=error msg="Error scraping for collect.info_schema.tables: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:56 mysql mysqld_exporter[23547]: time="2020-06-15T12:33:56+02:00" level=error msg="Error scraping for collect.info_schema.innodb_cmpmem: context deadline exceeded" source="exporter.go:171"
Jun 15 12:33:57 mysql mysqld[17375]: 2020-06-15 12:33:57 106026 [Warning] Aborted connection 106026 to db: 'unconnected' user: 'mysqld_exporter' host: '192.168.1.200' (Got an error writing communication packets)
Jun 15 12:33:58 mysql mysqld_exporter[23547]: 2020/06/15 12:33:58 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:58)
`

The exporter is on the same VM than the MariaDB server, connecting via local IP 192.168.1.200.

I have some datas, but a LOT of gaps in my metrics.

MySQL's user is configured with MAX_USER_CONNECTIONS=5 (2 was advised in the tutorial I used)

Any idea of what could cause those error (and if there is a way to correct that) ?

Thanks !

**Comment by foo-source** [comment]
Hi, where is the log path?

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ragsarang** [comment]
I was facing this issue due to max connections reached. I increased the max_connections parameter in database and then released some connections.
It was able to scrape again.
