### ISSUE TITLE
make build is error?

### ISSUE THREAD

**Issue by zhangchangwei** [prometheus/mysqld_exporter#481]
Build error   redhat 6.8   go .11

go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: gopkg.in/alecthomas/kingpin.v2@v2.2.6: unknown revision v2.2.6
go: finding gopkg.in/ini.v1 v1.57.0
go: gopkg.in/ini.v1@v1.57.0: unknown revision v1.57.0
go: github.com/gopherjs/gopherjs@v0.0.0-20190430165422-3e4dfb77656c: unknown revision 3e4dfb77656c
go: error loading module requirements
make: *** [common-lint] Error 1

**Comment by SuperQ** [comment]
Go 1.13 or newer is required.
