### ISSUE TITLE
go: github.com/DATA-DOG/go-sqlmock@v1.4.1: Get https://proxy.golang.org/github.com/%21d%21a%21t%21a-%21d%21o%21g/go-sqlmock/@v/v1.4.1.mod: dial tcp 34.64.4.113:443: i/o timeout

### ISSUE THREAD

**Issue by zhangchangwei** [prometheus/mysqld_exporter#482]
Why does the local path request such a request when it has a dependency package

**Comment by zhangguanzhang** [comment]
if you use go which version is 1.13+ and `GO111MODULE` set on, your build command should like this:
```
go build -mod=vendor xxx.go
```

**Comment by zhangchangwei** [comment]
> if you use go which version is 1.13+ and `GO111MODULE` set on, your build command should like this:
> 
> ```
> go build -mod=vendor xxx.go
> ```
 thank you very much, it's ok,thanks
