### ISSUE TITLE
No data point for all series using $__interval

### ISSUE THREAD

**Issue by RomainNakedCat** [prometheus/mysqld_exporter#521]
### Host operating system: output of `uname -a`
`Linux monitoring 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
### mysqld_exporter version: output of `mysqld_exporter --version`
```
mysqld_exporter, version 0.12.1 (branch: HEAD, revision: 48667bf7c3b438b5e93b259f3d17b70a7c9aff96)
  build user:       root@0b3e56a7bc0a
  build date:       20190729-12:35:58
  go version:       go1.12.7
```

### mysqld_exporter command line flags
None

### What did you do that produced an error?
Nothing
### What did you expect to see?
Some datas

### What did you see instead?

Nothing

In grafana 7.3.6 and prometheus 2.24 all series using $__interval are not returning anydata (I tried grafana 6.X.X and it does not work either). The data is stored in Prometheus, if you want to display datas you have to replace $__interval by a value like 5m. I dont know how to use $__interval or make it dynamic

Best regards,

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
