### ISSUE TITLE
Error scraping global state: Default addr for network '127.0.0.1' unknown

### ISSUE THREAD

**Issue by kvz** [prometheus/mysqld_exporter#53]
Hi, 

Thanks for this exporter! I'm trying to run `0.6.0`  it like so:

```bash
DATA_SOURCE_NAME=username:password@127.0.0.1/dbname prometheus-mysqld-exporter
```

But am running into:

```bash
INFO[0000] Error scraping global state: Default addr for network '127.0.0.1' unknown  file=mysqld_exporter.go line=697
```

Any idea what I'm doing wrong?

**Comment by SuperQ** [comment]
That's odd.  If you're scraping localhost, try `DATA_SOURCE_NAME='username:password@/`

mysqld_exporter doesn't require `/dbname`, but the golang SQL driver code requires atleast the `/` in the name for parsing.

**Comment by SuperQ** [comment]
Ahh, now I remember, the example on the mysqld_exporter README is very literal.

The upstream go SQL driver[0] requires the literal string `'(localhost:3306)'` if you specify it.

http://go-database-sql.org/accessing.html

**Comment by kvz** [comment]
Ah great, that fixed it for me - thanks a lot!

**Comment by SuperQ** [comment]
Great, please keep the feedback coming on the mysqld exporter.  If you have any other issues with specific collectors, there are some known performance issues with MySQL <= 5.6.  I don't have any older versions in production to test against.

**Comment by irocks04** [comment]
Hi,

I am getting the error Error scraping table schema: Default addr for network 'XXXXX:3306' unknown  file=mysqld_exporter.go line=836
INFO[0075] Error scraping global state: Default addr for network 'XXXXXXXXX' unknown  file=mysqld_exporter.go line=812
INFO[0075] Error scraping global variables: Default addr for network 'XXXXXXX:3306' unknown  file=mysqld_exporter.go line=81

I tried following the instructions but still ending up with the same error. The make file for some reason 
shows 
can't load package: package _/opt/mysqld_exporter-master: cannot find package "_/opt/mysqld_exporter-master" in any of:
        /usr/lib/golang/src/_/opt/mysqld_exporter-master (from $GOROOT)

**Comment by SuperQ** [comment]
@irocks04 That looks like you're not building in the correct path.

As for the exporter error, it looks like your DATA_SOURCE_NAME points to something invalid.

**Comment by irocks04** [comment]
Thanks for the reply. I am in the directory where we have the MakeFile and still shows that error

This is the data source i am using user:password@host:port/dbname
export DATA_SOURCE_NAME=exporter:asd123@xxxxxxx:3306/performance_schema

**Comment by SuperQ** [comment]
That syntax is incorrect.  It should be like this:
```
export DATA_SOURCE_NAME='exporter:asd123@(xxxxxxx:3306)/'
```

**Comment by irocks04** [comment]
Thank you So much. you made my day!!!!.

**Comment by irocks04** [comment]
Hi,

I had to set this up on another instance. I get read tcp 10.173.35.203:40536->10.173.35.180:9104: i/o timeout in prometheus status.

Any clue on this?

**Comment by macmoo2** [comment]
Good day

   While trying to run the mysqld_exporter on the database server directly , I get the following error : 

INFO[0000] Error scraping slave state: Error 1045: Access denied for user 'user'@'::1' (using password: YES)  file=mysqld_exporter.go line=824

    I have setup the user for both localhost and 127.0.0.1 , however it seems to be trying to use the ipv6 address, however we do not use ipv6 yet at all. 

      How can I resolve this. 

     using mysqld_exporter-0.7.1.linux-amd64


     Any assistance will be appreciated. 
     Thank you.

**Comment by SuperQ** [comment]
Usage questions are best asked on https://groups.google.com/forum/#!aboutgroup/prometheus-users
