### ISSUE TITLE
New feature request: metrics for global variables have_ssl and have_openssl

### ISSUE THREAD

**Issue by ChrisCGH** [prometheus/mysqld_exporter#547]
The global variables collector only produces metrics from variables which have numeric values at the moment.
I would like to get metrics corresponding to the global variables have_ssl and have_openssl which can take the values
YES or DISABLED - it should be fairly simple to map these onto 1 or 0 respectively.

**Comment by SuperQ** [comment]
This should be easy enough to support. We already pass this data to the `parseStatus()` helper. It looks like we just need to extend the parsing to include the new strings.

**Comment by ChrisCGH** [comment]
Thanks for the quick fix, will it be released soon?

**Comment by ChrisCGH** [comment]
@roidelapluie any idea when it is likely to be released? If it's not soon then we'll have to implement a work round to generate equivalent metrics via a cron job

**Comment by SuperQ** [comment]
I'm waiting for some feedback from a couple of beta testing users for the current release candidate. Once they give the OK I'll cut a new release.

**Comment by roidelapluie** [comment]
You could test the release candidate @ChrisCGH

**Comment by ChrisCGH** [comment]
@roidelapluie I don't see a rc with this fix in

**Comment by roidelapluie** [comment]
Indeed, it will be released in the final version, sorry :(

You can test the master branch (or :master docker tag)
