### ISSUE TITLE
Investigate metrics from `SHOW INNODB STATUS`

### ISSUE THREAD

**Issue by SuperQ** [prometheus/mysqld_exporter#55]
A ganglia plugin I found collects some metrics from `SHOW /*!50000 ENGINE*/ INNODB STATUS`.  Investigate what useful metrics could be recorded and add them to mysqld_exporter.

**Comment by roman-vynar** [comment]
We may take a look at this table http://dev.mysql.com/doc/refman/5.6/en/innodb-metrics-table.html (>=5.6) Also https://www.percona.com/blog/2014/11/18/mysqls-innodb_metrics-table-how-much-is-the-overhead/ to get something interesting rather that doing a raw parsing and hoping it won't be changed :)

**Comment by SuperQ** [comment]
We now have innodb_metrics table collection. :)
