### ISSUE TITLE
Multiple instances on a server

### ISSUE THREAD

**Issue by spihiker** [prometheus/mysqld_exporter#554]
When multiple mysql instances(eg:127.0.0.1:3306,127.0.0.1:3307) on a server,How to set up DATA_SOURCE_NAME?
Thanks.

**Comment by matthiasr** [comment]
You will need to run a separate exporter, with varying data source, for each MySQL process.

**Comment by spihiker** [comment]
But i can't execute :/usr/local/mysqld_exporter --DATA_SOURCE_NAME='........'  --web.listen-address='....'
Error:
   mysqld_exporter: error: unknown long flag '--DATA_SOURCE_NAME'
Thanks.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
