### ISSUE TITLE
Binaries for release 0.13.0

### ISSUE THREAD

**Issue by FraPazGal** [prometheus/mysqld_exporter#555]
Hello,

I just have a quick question. It seems the source code for the latest release, `0.13.0`, didn't include the binary assets released in every other release up to that point nor is it tagged as `latest release`. Would you be releasing the binaries at a later date (for the current or new releases) or would you be sticking to only the source code release?

Thanks,
Francisco de Paz

**Comment by roidelapluie** [comment]
Hello, indeed there was an issue with the CI. I have relaunched the build, it will be published ASAP. Thanks!

**Comment by roidelapluie** [comment]
Done :)
