### ISSUE TITLE
Disable collect.info_schema.tables by default

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/mysqld_exporter#56]
I suggest to disable collect.info_schema.tables by default. Having this enabled, even these are just 3 series mysql_info_schema_table_* will grow your disk space usage by Prometheus a lot depending from number of schemas and tables.

I think it would be better when the default behaviour is not to run huge selects from I_S and store so much data if people not intended to use it.

For example. in my case, with 2 prod hosts, 5s resolution, 5 day worth data, the basic set of metrics from node and mysqld exporters + mysql_info_schema_table_* I have got prometheus data reached 2.2G. When purging those 3 series via API, the space usage dropped down to 600M. I didn't plan to use those 3 series so far as I have a lot of tables. Of course, I can disable this option on exporter but bear with me, it's always better when defaults are not causing any impact.

**Comment by SuperQ** [comment]
That doesn't seem like a lot of space use to me.  We prefer to err on the side of collect more by default and let people turn off what they don't need.
