### ISSUE TITLE
How to add labels to the metrics

### ISSUE THREAD

**Issue by suguptacastlighthealth** [prometheus/mysqld_exporter#574]
Is there a way to add custom labels to the exposed metrics?

I have few environment variables like environment name, cluster name, hostname which I will like to be part of each metric.

Is there a way to do it?

**Comment by SuperQ** [comment]
This is the responsibility off the Prometheus configuration.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
