### ISSUE TITLE
Why did not export innodb_buffer_pool_pages_total metric？

### ISSUE THREAD

**Issue by yangliyl** [prometheus/mysqld_exporter#588]
https://github.com/prometheus/mysqld_exporter/blob/4e8e2b98de1c2bcfed7bf0a5c08b3a885b1cbf46/collector/global_status.go#L156-L157

**Comment by SuperQ** [comment]
This would break the calculation of `sum(mysql_global_status_buffer_pool_pages)`.

**Comment by yangliyl** [comment]
> This would break the calculation of `sum(mysql_global_status_buffer_pool_pages)`.

Is it okay to add a new metric mysql_global_status_buffer_pool_pages_total?

**Comment by SuperQ** [comment]
No, that would duplicate the data.

**Comment by yangliyl** [comment]
sum(mysql_global_status_buffer_pool_pages) == mysql_global_status_buffer_pool_pages_total ?
