### ISSUE TITLE
error spelling at file mysqld_exporter.go

### ISSUE THREAD

**Issue by weideguo** [prometheus/mysqld_exporter#591]
there is an error spelling at [here](https://github.com/prometheus/mysqld_exporter/blob/v0.13.0/mysqld_exporter.go#L277)
``` go
	level.Info(logger).Log("msg", "Starting msqyld_exporter", "version", version.Info())
```

**Comment by SuperQ** [comment]
Fixed in https://github.com/prometheus/mysqld_exporter/pull/602
