### ISSUE TITLE
mysql exporter user and password issue @

### ISSUE THREAD

**Issue by haipengzzz** [prometheus/mysqld_exporter#612]
I would like to ask you, how should I define the variable DATA_SOURCE_NAME when the "@" symbol appears in my mysql account or password?

**Comment by seaurching** [comment]
I have same issue. And my password contains #!@

**Comment by rafaelcanovas** [comment]
Having the same issue.

Just saw that @haipengzzz closed the issue.

How do you managed to solve it?

**Comment by tumichnix** [comment]
@haipengzzz How do you solve it?

**Comment by Amrish-Sharma** [comment]
Have you tried giving username/password containing @ within single quote( ' )?

**Comment by tumichnix** [comment]
Sorry for the late feedback. With the following ".my.cnf" it works with Azure:

`[client]
    host=HOST.mariadb.database.azure.com 
    user=USER@HOST
    password=PASSWORD`
