### ISSUE TITLE
How to display environment variables in metrics

### ISSUE THREAD

**Issue by laoxiaokang** [prometheus/mysqld_exporter#614]
I want to get the ip and port information of the monitoring target in metrics

**Comment by laoxiaokang** [comment]
like this:

# HELP mysql_version_info MySQL version and distribution.
# TYPE mysql_version_info gauge
mysql_version_info{innodb_version="5.7.33",version="5.7.33",version_comment="MySQL Community Server (GPL)"} 1

**Comment by laoxiaokang** [comment]
@SuperQ

**Comment by SuperQ** [comment]
IP and port information comes from the `instance` label.

Displaying random environment variables is out of scope for this exporter.
