### ISSUE TITLE
Systemd $HOME variable

### ISSUE THREAD

**Issue by d4nnyx** [prometheus/mysqld_exporter#633]
I'm trying to run mysqld_exporter as a systemd service. Problem is that exporter tries to find $HOME/.my.cnf, but systemd does not inherit this kind of environment variables. So only solution could by define `Environment=HOME=%h` in [Service] section of the service unit. But `%h`  is not dependent on `User=` settings, so I'm forced now to use `root` user for running exporter. 

Do you know some other way how to always get the right $HOME variable in systemd?

**Comment by roidelapluie** [comment]
> $USER, $LOGNAME, $HOME, $SHELL
> User name (twice), home directory, and the login shell. The variables are set for the units that have User= set, which includes>  user systemd instances. See [passwd(5)](http://linux.die.net/man/5/passwd)

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment%20Variables%20Set%20or%20Propagated%20by%20the%20Service%20Manager
