### ISSUE TITLE
Expose Errors as metrics; Skip errors

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#65]
Hi,

Right now if there is any error during scraping it looks like it is  reports error in error log and aborts. This makes it rather fragile ie if there is some format change between MySQL versions.

I would suggest

1) do not abort capture process on error just skip given data source

2) Additionally add metrics which show when capture of given data source has failed  (similar as metrics are available about prometheus server data captures)

This would allow to monitor and react on the problems on Prometheus itself rather than data not coming in (which also might be disabled capture)

The code in question:

if *collectPerfFileEvents {
		if err = scrapePerfFileEvents(db, ch); err != nil {
			log.Println("Error scraping performance schema:", err)
			return

**Comment by SuperQ** [comment]
https://github.com/prometheus/mysqld_exporter/pull/84 will fix this.

**Comment by SuperQ** [comment]
Fixed, will cut a release with this soon.
