### ISSUE TITLE
Make  Handler statistics reported through extra label 

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#66]
The Com_XXX handling in Prometheus is great as it allows me to get graph and be forward compatible with future versions and variants which can expose different commands

Handler_XXX is same and it would be great if it reported the same way

**Comment by SuperQ** [comment]
Yup, looks like a simple fix.

**Comment by SuperQ** [comment]
https://github.com/prometheus/mysqld_exporter/pull/68 out for review.

**Comment by roman-vynar** [comment]
Works fine for me :+1:

**Comment by SuperQ** [comment]
Thanks for the report.  I'll be cutting a new release this week.
