### ISSUE TITLE
The alarm is received at 12:00 every morning, but the service is normal

### ISSUE THREAD

**Issue by jxcwp** [prometheus/mysqld_exporter#668]
The alarm is received at 12:00 every morning, but the service is normal:
`[mysql] 2022/09/28 23:59:56 packets.go:37: unexpected EOF
[mysql] 2022/09/28 23:59:56 packets.go:37: unexpected EOF
[mysql] 2022/09/28 23:59:56 packets.go:37: unexpected EOF
ts=2022-09-28T15:59:56.635Z caller=exporter.go:149 level=error msg="Error pinging mysqld" err="driver: bad connection"
[mysql] 2022/09/28 23:59:58 packets.go:37: unexpected EOF
[mysql] 2022/09/28 23:59:58 packets.go:37: unexpected EOF
[mysql] 2022/09/28 23:59:58 packets.go:37: unexpected EOF
ts=2022-09-28T15:59:58.002Z caller=exporter.go:149 level=error msg="Error pinging mysqld" err="driver: bad connection"
[mysql] 2022/09/29 00:00:01 packets.go:37: unexpected EOF
[mysql] 2022/09/29 00:00:01 packets.go:37: unexpected EOF
[mysql] 2022/09/29 00:00:01 packets.go:37: unexpected EOF`

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
