### ISSUE TITLE
Support for INNODB_METRICS capture

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#67]
There is wealth of additional information available in INFORMATION_SCHEMA.INNODB_METRICS table. Many subsystems such as purging or working of index condition push down can be only analyzed using these metrics.

Relevant Documentation:
https://dev.mysql.com/doc/refman/5.7/en/innodb-information-schema-metrics-table.html

Only some of the metrics will be enabled by default.  User can enable more as needed with 

SET GLOBAL innodb_monitor_enable = [counter-name|module_name|pattern|all];

Exporter should only select rows with status = "enabled"

I would recommend grouping metrics based on the subsystem so it is easy to create graphs plotting all metrics for given subsystem if desired

Only COUNT value is really of any value

Example:

*************************** 217. row ***************************
           NAME: innodb_rwlock_x_spin_rounds
      SUBSYSTEM: server
          COUNT: 1903254040
      MAX_COUNT: 1903254040
      MIN_COUNT: NULL
      AVG_COUNT: 1343.9398661888538
    COUNT_RESET: 1903254040
MAX_COUNT_RESET: 1903254040
MIN_COUNT_RESET: NULL
AVG_COUNT_RESET: NULL
   TIME_ENABLED: 2016-01-02 10:48:18
  TIME_DISABLED: NULL
   TIME_ELAPSED: 1416175
     TIME_RESET: NULL
         STATUS: enabled
           TYPE: status_counter
        COMMENT: Number of rwlock spin loop rounds due to exclusive latch request

**Comment by SuperQ** [comment]
Seems reasonable.  I think the metrics would end up being named like: `mysql_info_schema_innodb_metrics_SUBSYSTEM{name="NAME"}`

There's a number of hints about thigns like `_usec` and the TYPE column has some strange things like `value` which seems like some kind of constant gauge.  There is also `counter` and `status_counter` which seem to be the same thing.  I'm not sure I can do anything with them, but I will probably expose the  TYPE as a label.

**Comment by PeterZaitsev** [comment]
Thanks Ben!,

I think this is good design allowing to access metrics individually as well as plot all or top metrics from subsystem.    I think it is good to expose type as a label

The difference between counter and status_counter is  what status_counter values are available as SHOW STATUS output as well.    

Yes some of these data points are really gauges.

**Comment by SuperQ** [comment]
Merged https://github.com/prometheus/mysqld_exporter/pull/69
