### ISSUE TITLE
Find hostname or IP Address

### ISSUE THREAD

**Issue by sandeepmuthathi** [prometheus/mysqld_exporter#671]
I'm using the dockerised version of mysqld_exporter to monitor our mysql DB instances. Is there any metrics that we have to get the server IP address/hostname to identify my DB instances? Or if not, how can we add it?

**Comment by SuperQ** [comment]
This is a job for service discovery.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
