### ISSUE TITLE
mysqld.address does not work

### ISSUE THREAD

**Issue by HelloWorDomain** [prometheus/mysqld_exporter#675]
start mysqld_exporter fail with --mysqld.address=
I find the argument at mysqld_exporter README.
But it doesn't work at this function.

----------
[root@localhost mysqld_exporter-0.14.0.linux-amd64]# ./mysqld_exporter --config.my-cnf='.my.cnf' --mysqld.address=192.168.10.188:3306
mysqld_exporter: error: unknown long flag '--mysqld.address', try --help
-----------

**Comment by SuperQ** [comment]
That is a not yet released feature. To find out what options are available, use `--help`.

**Comment by antiper27** [comment]
hello，I want to know，when this feature will be released? Thanks in advance。
