### ISSUE TITLE
When would 0.15.0 will release?

### ISSUE THREAD

**Issue by mingregister** [prometheus/mysqld_exporter#676]
When would 0.15.0 will release? The Multi-target feature is attractive to me.   

Can I Just use the main branch  in production environment?

**Comment by MattiasAng** [comment]
I am biased as I introduced multi-target/probe endpoint but we are using it in production for 50-60 instances without any issues since the commit.

There are a few config hiccups and documentation that needs to be taken care of but other than that, you should be good to go.

**Comment by mingregister** [comment]
I use the main branch in our production for 10+ instances, and everything is fine.

**Comment by nthienan** [comment]
I used the main branch in our production for 600+ instances. it works very well
