### ISSUE TITLE
Multi-target support not working as described in README.md

### ISSUE THREAD

**Issue by magiclobster** [prometheus/mysqld_exporter#685]
Multi-target scraping is not working as described

### Host operating system: output of `uname -a`
official debian-bullseys docker image
Linux aa8c1b0705ce 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

### mysqld_exporter version: output of `mysqld_exporter --version`
mysqld_exporter, version 0.14.0 (branch: HEAD, revision: ca1b9af82a471c849c529eb8aadb1aac73e7b68c)
  build user:       root@401d370ca42e
  build date:       20220304-16:25:15
  go version:       go1.17.8
  platform:         linux/amd64

### mysqld_exporter command line flags
None, .my.cnf placed in home directory

### .my.cnf configuration
[client]
user=monitoring
password=xXx

[client.servers]
user=monitoring
password=xXx

### What did you do that produced an error?
curl http://127.0.0.1:9104/probe?target=hostname:3306
curl http://127.0.0.1:9104/probe?target=hostname:3306&auth_module=client
curl http://127.0.0.1:9104/metrics?target=hostname:3306
curl http://127.0.0.1:9104/metrics?target=hostname:3306&auth_module=client

### What did you expect to see?
mysql metrics

### What did you see instead?
when using the /metrics endpoint only the exporter metrics are shown
mysql_exporter logs the following:
caller=exporter.go:149 level=error msg="Error pinging mysqld" err="dial tcp 127.0.0.1:3306: connect: connection refused"

When putting host=hostname and port=3306 into .my.cnf i can scrape the single node without problems.

Is multi target scraping working?
What is the correct endpoint? /probe as stated in the README doesn't work.
/metrics endpoint works but does not read the target url parameter

can somebody give me a hint please :)

**Comment by nthienan** [comment]
@magiclobster you have to compile mysqld_exporter from the source code yourself. Please don't use the latest release. That version is not supported multi-targets yet.

**Comment by magiclobster** [comment]
Thank you @nthienan 
Works like a charm

`FROM golang:1.18-bullseye as builder

RUN apt-get update && apt-get install -y \
        build-essential \
        g++ \
        make \
        git \
        mariadb-server

RUN mkdir /build \
  && cd /build \
  && git clone https://github.com/prometheus/mysqld_exporter \
  && cd /build/mysqld_exporter

RUN service mariadb start \
    && mysql -u root -e "CREATE OR REPLACE USER 'root'@'localhost' IDENTIFIED BY ''; GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION; FLUSH PRIVILEGES;" \
    && cd /build/mysqld_exporter \
    && make`
Now it works like described :)

**Comment by egarbi** [comment]
Can anyone explain how to setup the mono target (I guess old) mode? The docs only mention this one
