### ISSUE TITLE
--mysqld.address parameter not found

### ISSUE THREAD

**Issue by mak241265** [prometheus/mysqld_exporter#696]
Hello everyone..
I have a running MySQL and iam trying to run a MySQL exporter from another host which can create a metric from my running mysql..
i found there is parameter called mysql.address which can be passed to mysqld_exporter but unfortunately the mysqld_exporter does not recognise it...
### Host operating system: output of `uname -a`
Ubuntu 20.04.3 LTS
### mysqld_exporter version: output of `mysqld_exporter --version`
mysqld_exporter, version 0.14.0

### mysqld_exporter command line flags
--config.my-cnf /etc/.mysqld_exporter.cnf \
--collect.global_status \
--collect.info_schema.innodb_metrics \
--collect.auto_increment.columns \
--collect.info_schema.processlist \
--collect.binlog_size \
--collect.info_schema.tablestats \
--collect.global_variables \
--collect.info_schema.query_response_time \
--collect.info_schema.userstats \
--collect.info_schema.tables \
--collect.perf_schema.tablelocks \
--collect.perf_schema.file_events \
--collect.perf_schema.eventswaits \
--collect.perf_schema.indexiowaits \
--collect.perf_schema.tableiowaits \
--collect.slave_status \
--web.listen-address=x.x.x.x:9104 \
--mysqld.address=x.x.x.x:30008

### What did you do that produced an error?
mysqld_exporter[2095841]: mysqld_exporter: error: unknown long flag '--mysqld.address', try --help
### What did you expect to see?
expect the service works without the problem

**Comment by bondif** [comment]
I had the same issue, any solution yet?

**Comment by jmorille** [comment]
Still no fix ?

**Comment by dometec** [comment]
this option will be available on the next release (next to 0.14.0)...
