### ISSUE TITLE
core-dump

### ISSUE THREAD

**Issue by shuncon** [prometheus/mysqld_exporter#697]
vim /etc/systemd/system/mysqld_exporter.service
[Unit]
Description=mysqld_exporter service
Wants=network-online.target
After=network-online.target
[Service]
Environment=DATA_SOURCE_NAME=exporter:shun123@tcp/
ExecStart= /data/mysqld_exporter/mysqld_exporter
#Restart=on-failure
StandardOutput=syslog
StandardError=syslog
[Install]
WantedBy=multi-user.target

os: centos7
Dec 14 09:24:57 shun systemd[1]: Started mysqld_exporter service.
Dec 14 09:24:57 shun systemd[1]: mysqld_exporter.service: Main process exited, code=dumped, status=11/SEGV
Dec 14 09:24:57 shun systemd[1]: mysqld_exporter.service: Failed with result 'core-dump'.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
