### ISSUE TITLE
Support MySQL 5.7 Performance Schema

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#70]
Hi,

Getting this error running mysqld_exporter on 5.7

time="2016-01-25T12:57:29-05:00" level=info msg="Error scraping performance schema: Error 1054: Unknown column 'COUNT_WRITE_DELAYED' in 'field list'" file="mysqld_exporter.go" line=796
time="2016-01-25T12:57:29-05:00" level=info msg="Starting Server: :9304" file="mysqld_exporter.go" line=1747

Note it also would be helpful if error level would contain what "collector" is causing it or at very least actual failing query so it would be easier to troubleshoot it.

**Comment by SuperQ** [comment]
Yea, I found a few places where the error messages are pretty stupid.  Should be fixable.

**Comment by SuperQ** [comment]
Fix is up: https://github.com/prometheus/mysqld_exporter/pull/106

**Comment by SuperQ** [comment]
Fixed!

**Comment by PeterZaitsev** [comment]
Thank you!
