### ISSUE TITLE
How can I monitor mysql IO and SQL thread

### ISSUE THREAD

**Issue by l1douhua** [prometheus/mysqld_exporter#703]
I did not see the corresponding information in metrics

**Comment by yakirgb** [comment]
Do you mean replica IO/SQL status?
Just add `--collect.slave_status` , if you using `pt-heartbeat` you can add also `--collect.heartbeat --collect.heartbeat.table heartbeat_vie`

**Comment by l1douhua** [comment]
@yakirgb  mysql slave   IO and SQL thread

**Comment by yakirgb** [comment]
Check:
```
mysql_slave_status_slave_io_running
mysql_slave_status_slave_sql_running
```

**Comment by l1douhua** [comment]
mysql_slave_status_slave_io_running
mysql_slave_status_slave_sql_running

they are not in my prometheus
 I am using version  is mysqld_exporter-0.14.0 
@yakirgb 

![image](https://user-images.githubusercontent.com/49056512/212865817-78aa6e56-49da-4520-b785-40d94056174f.png)

**Comment by yakirgb** [comment]
> Just add --collect.slave_status

Did you add `--collect.slave_status` ??

**Comment by l1douhua** [comment]
yes  @yakirgb 

![image](https://user-images.githubusercontent.com/49056512/212868532-9a9cfa8b-4fbf-4515-8ba0-c8dd82241686.png)

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
