### ISSUE TITLE
Report more information from PROCESSLIST

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#71]
Hi,

Right now PROCESSLIST is parsed and number of gauges are created based on status

mysql_info_schema_threads{state="after create"} 0
mysql_info_schema_threads{state="altering table"} 0

It would be nice if we also report total query execution time (as sum) and longest query execution time, excluding replication.

This is very helpful for alerting on run away queries as query will not appear in the slow query log etc until it is complete and single run away query running for 3 hours can do a lot of damage.

**Comment by SuperQ** [comment]
Yea, I've been trying to come up with some good ways to find stuck queries
without too much processlist parsing.  But it seems to be the only way to
report such things.

**Comment by PeterZaitsev** [comment]
You can run another query on information_schema or performance_schema to capture longest currently running query but it is best to capture it from the same processlist capture.  There are systems with 10K+ connections where repeated running queries scans get expensive.

**Comment by SuperQ** [comment]
PR is up: https://github.com/prometheus/mysqld_exporter/pull/87

**Comment by SuperQ** [comment]
Merged
