### ISSUE TITLE
Import data from INNODB_SYS_TABLESPACES

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#72]
Hi,

This is available in MySQL 5.7 

mysql> select * from INFORMATION_SCHEMA.INNODB_SYS_TABLESPACES where name='sbinnodb/sbtest1' \G
*************************** 1. row ***************************
         SPACE: 42
          NAME: sbinnodb/sbtest1
          FLAG: 33
   FILE_FORMAT: Barracuda
    ROW_FORMAT: Dynamic
     PAGE_SIZE: 16384
 ZIP_PAGE_SIZE: 0
    SPACE_TYPE: Single
 FS_BLOCK_SIZE: 4096
     FILE_SIZE: 245937209344
ALLOCATED_SIZE: 245937266688
1 row in set (0.00 sec)

FILE_SIZE in this table is especially valuable because it is being updated in real time unlike  INFORMATION_SCHEMA.TABLES,  which is updated periodically and sometimes several GB off.

**Comment by SuperQ** [comment]
Looks like good data.  Should be easy to implement.

**Comment by SuperQ** [comment]
PR: https://github.com/prometheus/mysqld_exporter/pull/116

**Comment by SuperQ** [comment]
Released in 0.8.0
