### ISSUE TITLE
Feature request: support collector configuration via config file

### ISSUE THREAD

**Issue by maxenglander** [prometheus/mysqld_exporter#759]
I would like the ability to dynamically change active collectors, so that when a database is having issues I can turn on more collectors, and turn them back off after the issue is resolved.

What I have in mind to make this work:

 1. Support configuring collectors via config file (this issue).
 2. Support reloading collector configuration from config file with `/-/reload` endpoint is touched.

**Comment by SuperQ** [comment]
We have no plans to create a configuration for this.

**Comment by maxenglander** [comment]
@SuperQ would you be open to a contribution?
