### ISSUE TITLE
Split Buffer Pool Stats in the separate dimension

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#76]
Innodb SHOW GLOBAL STATUS naming for Buffer Pool Stats is not very consistent

| Innodb_buffer_pool_pages_data           | 1538216                                          |
| Innodb_buffer_pool_bytes_data           | 25202130944                                      |
| Innodb_buffer_pool_pages_dirty          | 576509                                           |
| Innodb_buffer_pool_bytes_dirty          | 9445523456                                       |
| Innodb_buffer_pool_pages_flushed        | 11392163927                                      |
| Innodb_buffer_pool_pages_free           | 5684                                             |
| Innodb_buffer_pool_pages_LRU_flushed    | 0                                                |
| Innodb_buffer_pool_pages_made_not_young | 58313675407                                      |
| Innodb_buffer_pool_pages_made_young     | 1327142363                                       |
| Innodb_buffer_pool_pages_misc           | 28772                                            |
| Innodb_buffer_pool_pages_old            | 567754                                           |
| Innodb_buffer_pool_pages_total          | 1572672                                          |
| Innodb_buffer_pool_read_ahead_rnd       | 0                                                |
| Innodb_buffer_pool_read_ahead           | 11540243                                         |
| Innodb_buffer_pool_read_ahead_evicted   | 0                                                |
| Innodb_buffer_pool_read_requests        | 338888865574                                     |
| Innodb_buffer_pool_reads                | 17291274739                                      |
| Innodb_buffer_pool_wait_free            | 17007371       

Some of these correspond to actions and others to state of buffer pool.  I would suggest so split 

Innodb_buffer_pool_pages_total consists of 

Innodb_buffer_pool_pages_data, Innodb_buffer_pool_pages_dirty, Innodb_buffer_pool_pages_free, Innodb_buffer_pool_pages_misc  

should be separately available so it is easy to have the graph for all buffer pool content

**Comment by SuperQ** [comment]
Ok, I think this does what you want: https://github.com/prometheus/mysqld_exporter/pull/101

**Comment by SuperQ** [comment]
Fixed
