### ISSUE TITLE
Let mysqld_exporter run sql query.

### ISSUE THREAD

**Issue by algo7** [prometheus/mysqld_exporter#778]
In some cases, it will be useful to have mysqld_exporter execute some SQL queries. We have this use case that we run a certain query on an interval to check for certain values in the database. If it's not within the defined range of values, an alert will be triggered.

Similar function exists in Datadog:
https://docs.datadoghq.com/integrations/guide/mysql-custom-queries/

There is a community exporter that is able to something similar:
https://github.com/albertodonato/query-exporter

Is it possible to implement it in the official mysqld_exporter?

**Comment by SuperQ** [comment]
No, this is not supported. The mysqld_exporter is for monitoring the mysql server process, not any values in databases. A query exporter like the one you mentioned is required for business metrics.

* https://github.com/justwatchcom/sql_exporter

**Comment by algo7** [comment]
> No, this is not supported. The mysqld_exporter is for monitoring the mysql server process, not any values in databases. A query exporter like the one you mentioned is required for business metrics.
> 
>     * https://github.com/justwatchcom/sql_exporter

But is it possible to have any official alternative?
