### ISSUE TITLE
INNODB_METRICS does not handle some of the data

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#83]
Hi,

After enabling it on 5.7 getting:

o a uint64: strconv.ParseUint: parsing \"-1\": invalid syntax" file="mysqld_exporter.go" line=830
time="2016-02-14T14:42:24-05:00" level=info msg="Error scraping information_schema.innodb_metrics: sql: Scan error on column index 4: converting string \"-1\" to a uint64: strconv.ParseUint: parsing \"-1\": invalid syntax" file="mysqld_exporter.go" line=830
time="2016-02-14T14:42:25-05:00" level=info msg="Error scraping information_schema.innodb_metrics: sql: Scan error on column index 4: converting string \"-1\" to a uint64: strconv.ParseUint: parsing \"-1\": invalid syntax" file="mysqld_exporter.go" line=830
time="2016-02-14T14:42:26-05:00" level=info msg="Error scraping information_schema.innodb_metrics: sql: Scan error on column index 4: converting string \"-1\" to a uint64: strconv.ParseUint: parsing \"-1\": invalid syntax" file="mysqld_exporter.go" line=830
time="2016-02-14T14:42:27-05:00" level=info msg="Error scraping information_schema.innodb_metrics: sql: Scan error on column index 4: converting string \"-1\" to a uint64: strconv.ParseUint: parsing \"-1\": invalid syntax" file="mysqld_exporter.go" line=830

It might be caused by this: mysql> select * from innodb_metrics where count=-1  \G
*************************** 1. row ***************************
           NAME: metadata_table_reference_count
      SUBSYSTEM: metadata
          COUNT: -1
      MAX_COUNT: 18
      MIN_COUNT: -1
      AVG_COUNT: -0.001092896174863388
    COUNT_RESET: -1
MAX_COUNT_RESET: 18
MIN_COUNT_RESET: -1
AVG_COUNT_RESET: NULL
   TIME_ENABLED: 2016-02-14 14:29:20
  TIME_DISABLED: NULL
   TIME_ELAPSED: 915
     TIME_RESET: NULL
         STATUS: enabled
           TYPE: counter
        COMMENT: Table reference counter
1 row in set (0.00 sec)

This might be server bug having count=1 but it is not reason to abort

**Comment by SuperQ** [comment]
Ahh, it looks like schema on MySQL 5.6 is
```
`COUNT` bigint(21) NOT NULL DEFAULT '0',
```

So casting to unit64 is incorrect.  But we will need to special-case this anyway as prometheus counters are unsigned.

**Comment by PeterZaitsev** [comment]
I do not think it would be as big deal if it is truncated or skipped all together. Now it just kills all other counters.

I think for data capture it would be better to make exporters much more forgiving - right now they seems to abort when any issue is encountered

**Comment by SuperQ** [comment]
Yea, It's been on my todo list to fix that flaw in the exporter.

**Comment by SuperQ** [comment]
So, argh, `metadata_table_reference_count` is labeled a counter, but it's a gauge.  :tableflip:

**Comment by SuperQ** [comment]
http://bugs.mysql.com/bug.php?id=75966

**Comment by SuperQ** [comment]
Please give this branch a try: https://github.com/prometheus/mysqld_exporter/pull/85

**Comment by PeterZaitsev** [comment]
Thanks!    Innodb_metrics are very helpful for advanced investigations yet as they are not as mature as SHOW STATUS I think they are more buggy.   As we get them used more actively I think they will get more love and attention.

**Comment by SuperQ** [comment]
Merged fix.
