### ISSUE TITLE
WSREP - Cluster monitoring

### ISSUE THREAD

**Issue by nser77** [prometheus/mysqld_exporter#847]
Hi community, I'm just wondering if there is some way to monitor GALERA cluster with `mysqld_exporter` and status variables.

**Comment by bebehei** [comment]
You usually monitor the state via `SHOW GLOBAL VARIABLES;` or `SHOW GLOBAL STATUS;`.

mysqld exporter can export this output as prometheus metrics.

You have to enable the collector flags `collector.global_status` and `collector.global_variables`. You have the data then and can build your own dashboard.

For the collector flags, see the README file with the docs:

https://github.com/prometheus/mysqld_exporter?tab=readme-ov-file#collector-flags
