### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by robertsilen** [prometheus/mysqld_exporter#857]
Hello, I noticed prometheus-mysqld-exporter has a suggested dependency on the MySQL default variant in Ubuntu (see https://tracker.debian.org/pkg/prometheus-mysqld-exporter) - I can't find anything in the documentation mentioning mysql, nor mariadb. Which ones have you tested on? I'd like to suggest the ubuntu package to be dependent on mariadb explicitly on mariadb if that reflects practise? Thank you for comments on this. 

This is part of my efforts I describe in my blog [Improving MariaDB Support in Open Source Projects](https://mariadb.org/improving-mariadb-support-in-open-source-projects/).

**Comment by SuperQ** [comment]
We test on MySQL, percona-server, and mariadb. 

This is mentioned in the README.md
