### ISSUE TITLE
MySQL metric variables name change proposal

### ISSUE THREAD

**Issue by frenkye** [prometheus/mysqld_exporter#858]
### mysqld_exporter version: output of `mysqld_exporter --version`
```
mysqld_exporter, version 0.15.0 (branch: HEAD, revision: 6ca2a42f97f3403c7788ff4f374430aa267a6b6b)
  build user:       root@c4fca471a5b1
  build date:       20230624-04:09:04
  go version:       go1.20.5
  platform:         linux/amd64
  tags:             netgo
```
### mysqld_exporter command line flags
```
    --collect.global_status
    --collect.global_variables
    --collect.slave_status
    --collect.mysql.user
    --collect.info_schema.processlist
    --no-collect.info_schema.innodb_metrics
    --no-collect.info_schema.tables
```

### Issue / Problem
This is on more side how to work with the data. I wanted to show all changes in variables on dashboard via annotations for that u can do something like this:
```
changes(mysql_global_variables_aria_log_file_size{instance="$instance"}[5m])
```
You will get into problem when trying to do all available variables:
```
changes({__name__=~"mysql_global_variables.+",instance="$instance"}[5m])
```

I would like to suggest change the metric names from: `mysql_global_variables_VARIABLE_NAME{labels=...}` to something like: `mysql_global_variables{name="VARIABLE_NAME", labels=...}`

This would be better overall for working with this kind of data. If someone knows how this could be done with current metrics, help would be much appreciated.

Guess, this would benefit `mysql_global_status_.+` as well.

**Comment by SuperQ** [comment]
Having separate metric names is intentional for most cases. The reason is because metric names are intended to denote different values for different things. 

Making use of labels means that the underlying value is related to other values with the same metric name.

It becomes nonsensical if you apply functions like `sum(mysql_global_variables)`, because something like  `mysql_global_variables{variable="max_error_count"} + mysql_global_variables{variable="max_heap_table_size"}` makes no sense. They are completely different _metrics_.

So no, I don't think this is something we would want to do. It doesn't match with Prometheus best practices.

**Comment by SuperQ** [comment]
Your use case can be solved reasonably easily tho with `label_replace()` and subquery syntax.

```
changes(
  label_replace(
    {__name__=~"mysql_global_variables_.*"},
    "variable_name",
    "$1",
    "__name__",
    "mysql_global_variables_(.*)"
  )[5m:15s]
)
```

**Comment by frenkye** [comment]
I tried the label_replace, but could not get it to work.

Thank you.

**Comment by dellnoantechnp** [comment]
![image](https://github.com/user-attachments/assets/be9bc111-08b2-45a9-b4dc-07c4a5775e21)
The new `prom/mysqld-exporter` image tag `main` is already fine.

Not have `syntax to use near 'SLAVE HOSTS'` log:
```log
mysqld-exporter  | ts=2024-05-15T02:39:40.760Z caller=exporter.go:173 level=error msg="Error from scraper" scraper=slave_status target=mysql_replica:3306 err="Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE STATUS' at line 1"
mysqld-exporter  | ts=2024-05-15T02:43:26.471Z caller=exporter.go:173 level=error msg="Error from scraper" scraper=slave_hosts target=mysql_replica:3306 err="Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE HOSTS' at line 1"
```
