### ISSUE TITLE
do not skip status_counter metrics from innodb_metrics

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/mysqld_exporter#86]
Hi,

Currently such metrics are skipped probably based on wrong suggestion by me what they are duplicated in SHOW GLOBAL STATUS.    Most are not in MySQL 5.7 !

	infoSchemaInnodbMetricsQuery = `
		SELECT
		  name, subsystem, type, comment,
		  count
		  FROM information_schema.innodb_metrics
		  WHERE status = 'enabled'
		    AND type != 'status_counter'

We need to remove  type !='status_counter' from here and treat such metrics as count metrics

Sorry for confusion.

**Comment by SuperQ** [comment]
Lol, oracle, no sense of design.  Why didn't those should change to `counter`?
